#!/usr/bin/env python3
"""
G-2a-S1 INDEPENDENT SECOND LEG (CC, from scratch) — Route-1 necessary-condition screen
for the soliton spin-isospin locking (§2.87.A).

Independent on every axis vs the chat-side first leg:
  - 2O built as 2x2 SU(2) MATRICES, generated by closure under MATRIX multiplication
    (first leg: unit-quaternion list + quaternion multiply).
  - spin-j characters via CHEBYSHEV chi_j = U_{2j}(tr/2)  (first leg: 2cos3phi+2cos phi).
  - own conjugacy-class + quotient computation for the genuine-irrep count D1.
  - own commutant solver for D2.
Pure finite-group + Lie rep theory. M.CW ceiling = R2 (admissibility); the screen
CANNOT return the dynamical locking fact. Eddington: the factor-of-4 is the screened
object, nothing is fit. (The 2O character table is standard/textbook — this is a light
confirmatory screen, not a novel result.)
"""
import numpy as np
from itertools import product

def quat_to_su2(w,x,y,z):
    return np.array([[w+1j*x, y+1j*z],[-y+1j*z, w-1j*x]], complex)

# ---- generate 2O by CLOSURE from two SU(2) generators (no quaternion list) ----
g1 = quat_to_su2(*( (1/np.sqrt(2))*np.array([1,1,0,0]) ))     # order 8 (binary 4-fold)
g2 = quat_to_su2(*( 0.5*np.array([1,1,1,1]) ))                # order 6 (binary 3-fold)
def key(M): return tuple(np.round(M.flatten(),6))
G={key(np.eye(2,dtype=complex)): np.eye(2,dtype=complex)}
frontier=[np.eye(2,dtype=complex)]
while frontier:
    A=frontier.pop()
    for g in (g1,g2):
        for B in (g@A, A@g):
            if key(B) not in G:
                G[key(B)]=B; frontier.append(B)
G=list(G.values())
mI=-np.eye(2,dtype=complex)
print("="*72); print("G-2a-S1 SECOND LEG (independent: SU(2) matrices + Chebyshev chars)"); print("="*72)
print(f"\n[group] |<g1,g2>| = {len(G)} (expect 48: binary octahedral 2O)")
print(f"        central -1 (the 2pi rotation -> -Id) in the group? {any(np.allclose(M,mI) for M in G)}   [NC1]")

# ---- spin-j characters via Chebyshev U_{2j}(tr/2) ----
def U(n,x):            # Chebyshev 2nd kind by recurrence; x may be array
    U0=np.ones_like(np.asarray(x,float));
    if n==0: return U0
    U1=2*np.asarray(x,float)
    if n==1: return U1
    for _ in range(2,n+1):
        U0,U1 = U1, 2*np.asarray(x,float)*U1 - U0
    return U1
def chi(j2, M):        # j2 = 2j (integer): dim = j2+1
    t = np.real(np.trace(M))/2.0
    return U(j2, t)
tr_half = np.array([np.real(np.trace(M))/2 for M in G])
def inner(j2a,j2b):
    return np.mean([chi(j2a,M)*np.conj(chi(j2b,M)) for M in G]).real

I=np.eye(2,dtype=complex)
print("\n--- NC2 : spin-3/2 = the genuine quartet (FR sign) ---------------------")
print(f"  chi_3/2(I)   = {chi(3,I):+.3f}   (quartet, dim 4)")
print(f"  chi_3/2(-I)  = {chi(3,mI):+.3f}   (central -> -Id : FR / spinor phase PRESENT)")
print(f"  <3/2,3/2>    = {inner(3,3):.4f}   -> single irrep? {abs(inner(3,3)-1)<1e-6}")
print(f"  chi_1(-I)    = {chi(2,mI):+.3f}   (spin-1: central -> +Id : BOSONIC, excluded)")
print(f"  chi_1/2(-I)  = {chi(1,mI):+.3f}   (spin-1/2: -> -Id, genuine; <1/2,1/2>={inner(1,1):.3f})")

# ---- conjugacy classes of 2O, and of the quotient O = 2O/{+-I} ----
def conj_classes(elems, mul, inv, keyf):
    idx={keyf(g):i for i,g in enumerate(elems)}
    seen=set(); classes=[]
    for g in elems:
        if keyf(g) in seen: continue
        orb=set()
        for h in elems:
            c=mul(mul(h,g),inv(h)); orb.add(keyf(c))
        classes.append(orb); seen|=orb
    return classes
cl2O = conj_classes(G, lambda a,b:a@b, lambda a:np.linalg.inv(a), key)
# quotient O = 2O/{+-I}: identify M with -M via a bulletproof min-key coset label
def cosetkey(M): return min(key(M), key(-M))
Ocos={}
for M in G:
    Ocos[cosetkey(M)] = M            # one representative matrix per coset
Oel=list(Ocos.values())
clO = conj_classes(Oel, lambda a,b:a@b, lambda a:np.linalg.inv(a), cosetkey)
print("\n--- D1 : forcing of the factor-of-4 quartet ---------------------------")
print(f"  #conjugacy classes of 2O   = {len(cl2O)}  (= # irreps; expect 8)")
print(f"  |O = 2O/{{+-I}}| = {len(Oel)} (expect 24); #classes of O = {len(clO)} (= #bosonic irreps; expect 5)")
n_gen = len(cl2O)-len(clO)
sumsq_bos = len(Oel)                       # sum d^2 over bosonic irreps = |O|
sumsq_gen = len(G)-sumsq_bos               # = 24
print(f"  genuine irreps = 8 - 5 = {n_gen};  sum d^2 (genuine) = 48 - {sumsq_bos} = {sumsq_gen}")
# spin-1/2 (dim2,genuine) and spin-3/2 (dim4,genuine) are two of them; even dims, sum 24
# => 16 + 4 + x = 24 => x = 4 => third genuine is dim 2 => exactly ONE dim-4 => D1=1
D1 = 1 if (n_gen==3 and sumsq_gen==24 and abs(inner(3,3)-1)<1e-6 and chi(3,mI)<0) else None
print(f"  spin-3/2 verified genuine (chi(-I)=-4) & irreducible (<3/2,3/2>=1) -> one dim-4 genuine")
print(f"  remaining genuine: 24-16-4(spin1/2)=4 -> a dim-2; so dims(genuine)=(2,2,4)")
print(f"  D1 = #(4-dim genuine irreps) = {D1}  -> quartet {'FORCED (unique)' if D1==1 else 'NOT unique'}   [NC2']")

# ---- D2 : commutant of color SU(3) (as 3+1) in M4(C) ----
gell=[np.array(M,complex) for M in [
 [[0,1,0],[1,0,0],[0,0,0]],[[0,-1j,0],[1j,0,0],[0,0,0]],[[1,0,0],[0,-1,0],[0,0,0]],
 [[0,0,1],[0,0,0],[1,0,0]],[[0,0,-1j],[0,0,0],[1j,0,0]],[[0,0,0],[0,0,1],[0,1,0]],
 [[0,0,0],[0,0,-1j],[0,1j,0]],(1/np.sqrt(3))*np.array([[1,0,0],[0,1,0],[0,0,-2]])]]
col=[np.zeros((4,4),complex) for _ in gell]
for k,L in enumerate(gell): col[k][:3,:3]=L
def commutant_dim(gens,n):
    rows=[]
    for Gm in gens:
        K=np.kron(Gm,np.eye(n))-np.kron(np.eye(n),Gm.T)   # vec([G,X])=0
        rows.append(K)
    s=np.linalg.svd(np.vstack(rows),compute_uv=False)
    return int(n*n-np.sum(s>1e-9*max(1,s[0])))
D2=commutant_dim(col,4)
print("\n--- D2 : transversality of locked spin-SU(2) to color ------------------")
print(f"  dim_C commutant of color-SU(3) (3+1) in M4(C) = {D2}  (Schur: 3,1 distinct -> C+C, abelian)")
print(f"  2O (order 48, NON-abelian) cannot sit in an abelian U(1) commutant: {'CONFIRMED' if D2<=2 else 'no'}")
print(f"  -> spin-SU(2) NOT hostable inside color SU(4); must be a SEPARATE TRANSVERSE factor.   [NC3]")
# transverse arena exists by construction (tensor product)
C_op=np.kron((1/np.sqrt(3))*np.diag([1,1,-2]).astype(complex), np.eye(2))
S_op=np.kron(np.eye(3), np.array([[0,1],[1,0]],complex))
tp=np.max(np.abs(C_op@S_op-S_op@C_op))
print(f"  tensor-product arena C(x)O(x)(spinSU2): max|[color(x)1, 1(x)spin]| = {tp:.1e} -> commute {tp<1e-9}")

print("\n"+"="*72); print("VERDICT (against the locked pre-registered arms)"); print("="*72)
passp = (D1==1) and (tp<1e-9) and (D2<=2)
print(f"  D1={D1}  D2={D2}  transverse arena={tp<1e-9}")
print("  -> PASS-possible (R2). NECESSARY CONDITION MET:" if passp else "  -> NOT pass; inspect")
print("     * factor-of-4 quartet FORCED (D1=1, unique genuine dim-4 irrep);")
print("     * FR/spinor phase present (chi_3/2(-I) = -4); bosonic sector excluded (chi_1(-I)=+3);")
print("     * locked spin-SU(2) NOT hostable in color SU(4) (commutant abelian, D2=2)")
print("       -> separate TRANSVERSE factor, supplied by the C(x)O(x)H arena §2.87.A forced.")
print("  CANNOT settle (M.CW): the dynamical locking fact, or Assignment I vs II. Greenlights Routes 2/3.")
print("  OUT OF SCOPE flag carried: NC5 (baryon 3-strand permutation under spatial rotation could")
print("    leak rotation into color, breaking transversality for the baryon) -- geometry-gated,")
print("    needs Routes 2/3 / M.ONT; the place a genuine obstruction could still live. CONFIRMS first leg.")
