#!/usr/bin/env python3
"""
c_sl27_crosscheck.py -- C2 batch, math_B leg, item (c): second route for the span / algebra numbers.

Independent of c_sl27.py (no shared code).  Two routes:

Route I (integer, characteristic 0).  The 8-dim principal series rho = sigma4 (+) sigma4' is built
a second way: as the space of functions f on F_7^2 \\ {0} with f(c v) = (c/7) f(v), G acting by
(g f)(v) = f(g^-1 v).  All matrices are integer (entries 0, +-1).  Exact ranks over Q via python-flint:
    rank span{rho(x) : x of order 4}            (module argument: equals the sigma4-span dimension,
                                                 because the image is a quotient of a multiplicity-free
                                                 module and sigma4' = conj(sigma4))
    rank span{rho(g) : g in G}                   (= 16 + 16 if sigma4, sigma4' are inequivalent irreducibles)
    dim of the algebra generated by the order-4 rho(x)
Route II (characteristic 11, where sqrt(-7) = 2 exists and 11 does not divide 336).
    sigma4 mod 11 obtained by splitting rho mod 11 with its commutant; span rank and generated algebra
    computed with nmod_mat.  (Supporting evidence only; Route I and c_sl27.py are exact in char 0.)
"""
import itertools
import flint

P = 7
SQ = {1, 2, 4}


def leg(c):
    return 1 if c % P in SQ else -1


def mat(a, b, c, d):
    return (a % P, b % P, c % P, d % P)


def mmul(A, B):
    a, b, c, d = A
    e, f, g, h = B
    return mat(a * e + b * g, a * f + b * h, c * e + d * g, c * f + d * h)


def minv(A):
    a, b, c, d = A
    return mat(d, -b, -c, a)  # det = 1


def apply(A, v):
    a, b, c, d = A
    return ((a * v[0] + b * v[1]) % P, (c * v[0] + d * v[1]) % P)


G = [mat(a, b, c, d) for a, b, c, d in itertools.product(range(P), repeat=4) if (a * d - b * c) % P == 1]
E = (1, 0, 0, 1)
NEG = (6, 0, 0, 6)


def order(A):
    k, R = 1, A
    while R != E:
        R, k = mmul(R, A), k + 1
    return k


# line representatives (first nonzero coordinate = 1)
reps = [(1, y) for y in range(P)] + [(0, 1)]


def line_rep(v):
    """return (index of the line through v, c) with v = c * rep."""
    x, y = v
    if x != 0:
        c = x
        r = (1, (y * pow(x, P - 2, P)) % P)
    else:
        c = y
        r = (0, 1)
    return reps.index(r), c


def rho(g):
    """(g f)(v) = f(g^-1 v) on the basis f_j (f_j(c * rep_j) = (c/7), zero off line j).
    Matrix entry [i][j] = (g f_j)(rep_i) = f_j(g^-1 rep_i)."""
    gi = minv(g)
    M = [[0] * 8 for _ in range(8)]
    for i, r in enumerate(reps):
        j, c = line_rep(apply(gi, r))
        M[i][j] = leg(c)
    return M


def matmul_int(A, B):
    return [[sum(A[i][k] * B[k][j] for k in range(8)) for j in range(8)] for i in range(8)]


def main():
    print("=" * 78)
    print("ITEM (c) cross-check (independent construction; python-flint exact ranks)")
    print("=" * 78)
    R = {g: rho(g) for g in G}
    import numpy as np
    RN = {g: np.array(R[g], dtype=np.int64) for g in G}
    homfail = sum(1 for g in G for h in G if not np.array_equal(RN[g] @ RN[h], RN[mmul(g, h)]))
    print(f"|G| = {len(G)}; homomorphism failures over all pairs: {homfail}")
    O4 = [g for g in G if order(g) == 4]
    chi = sorted({(order(g), sum(R[g][i][i] for i in range(8))) for g in G})
    print("character values (order, trace) occurring:", chi)
    print("rho(-I) = -Id:", R[NEG] == [[-1 if i == j else 0 for j in range(8)] for i in range(8)])

    # Route I: ranks over Q (integer matrices)
    A4 = flint.fmpz_mat([sum(R[x], []) for x in O4])
    AG = flint.fmpz_mat([sum(R[g], []) for g in G])
    print(f"Route I: number of order-4 elements = {len(O4)}")
    print(f"Route I: rank_Q span{{rho(x): ord x = 4}} = {A4.rank()}   (in M_8(Q), dim 64)")
    print(f"Route I: rank_Q span{{rho(g): g in G}}   = {AG.rank()}   (expect 32 = 16 + 16)")
    # algebra generated by order-4 images, closure under right multiplication (exact over Q)
    basis = [sum(R[x], []) for x in O4]
    cur_rank = flint.fmpq_mat(basis).rref()[1]
    while True:
        Mq, rk = flint.fmpq_mat(basis).rref()
        rows = [[Mq[i, j] for j in range(64)] for i in range(rk)]
        new = []
        for row in rows:
            B = [row[8 * i:8 * i + 8] for i in range(8)]
            for x in O4:
                prod = [[sum(B[i][k] * R[x][k][j] for k in range(8)) for j in range(8)] for i in range(8)]
                new.append(sum(prod, []))
        Mq2, rk2 = flint.fmpq_mat(rows + new).rref()
        if rk2 == rk:
            break
        basis = [[Mq2[i, j] for j in range(64)] for i in range(rk2)]
    print(f"Route I: dim_Q algebra generated by the order-4 rho(x) = {rk}  (expect 32 = dim End(sigma4) + dim End(sigma4'))")
    print(f"Route I: (starting span rank was {cur_rank})")

    # Route II: char 11
    p = 11
    r7 = 2  # 2^2 = 4 = -7 mod 11
    assert (r7 * r7 + 7) % p == 0
    F = lambda rows: flint.nmod_mat(rows, p)
    # commutant: X rho(g) = rho(g) X for generators u, l
    u, l = mat(1, 1, 0, 1), mat(1, 0, 1, 1)
    eqs = []
    for g in (u, l):
        Rg = R[g]
        for i in range(8):
            for j in range(8):
                row = [0] * 64
                for k in range(8):
                    row[i * 8 + k] += Rg[k][j]
                    row[k * 8 + j] -= Rg[i][k]
                eqs.append([x % p for x in row])
    ns, nullity = F(eqs).nullspace()
    print(f"Route II (p = {p}): commutant dimension mod p = {nullity}")
    vecs = [[int(ns[i, c]) for i in range(64)] for c in range(nullity)]
    T = None
    for v in vecs:
        Mv = [v[8 * i:8 * i + 8] for i in range(8)]
        if any(Mv[i][j] for i in range(8) for j in range(8) if i != j) or len({Mv[i][i] for i in range(8)}) > 1:
            T = Mv
            break
    TM = F(T)
    T2 = TM * TM
    # find alpha, beta with T^2 = alpha T + beta I (mod p)
    sol = None
    for al in range(p):
        for be in range(p):
            if T2 == al * TM + be * F([[1 if i == j else 0 for j in range(8)] for i in range(8)]):
                sol = (al, be)
    al, be = sol
    disc = (al * al + 4 * be) % p
    sq = [x for x in range(p) if (x * x - disc) % p == 0]
    inv2 = pow(2, p - 2, p)
    mu1, mu2 = ((al + sq[0]) * inv2) % p, ((al - sq[0]) * inv2) % p
    Id = F([[1 if i == j else 0 for j in range(8)] for i in range(8)])
    P1 = (TM - mu2 * Id) * pow((mu1 - mu2) % p, p - 2, p)
    print(f"Route II: T^2 = {al} T + {be} I mod {p}; eigenvalues {mu1}, {mu2}; rank P1 = {P1.rank()}; P1^2 == P1: {P1 * P1 == P1}")
    # basis of image(P1): independent columns
    P1l = [[int(P1[i, j]) for j in range(8)] for i in range(8)]
    cols = []
    for j in range(8):
        trial = cols + [[P1l[i][j] for i in range(8)]]
        if F(trial).rank() == len(trial):
            cols = trial
        if len(cols) == 4:
            break
    Bm = F([[cols[c][i] for c in range(4)] for i in range(8)])  # 8x4
    rowsel = []
    for i in range(8):
        trial = rowsel + [i]
        if F([[int(Bm[r, c]) for c in range(4)] for r in trial]).rank() == len(trial):
            rowsel = trial
        if len(rowsel) == 4:
            break
    Bsub = F([[int(Bm[r, c]) for c in range(4)] for r in rowsel])
    Binv = Bsub.inv()
    S = {}
    inv_ok = True
    for g in G:
        RB = F([[x % p for x in row] for row in R[g]]) * Bm
        Mg = Binv * F([[int(RB[r, c]) for c in range(4)] for r in rowsel])
        if RB != Bm * Mg:
            inv_ok = False
        S[g] = Mg
    print(f"Route II: invariant 4-dim subspace (rho(g)B = B sigma(g) for all g): {inv_ok}")
    span = F([[int(S[x][i, j]) for i in range(4) for j in range(4)] for x in O4])
    print(f"Route II: rank_F11 span{{sigma(x): ord x = 4}} = {span.rank()}")
    # algebra mod p
    basis = [[int(S[x][i, j]) for i in range(4) for j in range(4)] for x in O4]
    while True:
        Mb = F(basis)
        rk = Mb.rank()
        rr = Mb.rref()[0]
        rows = [[int(rr[i, j]) for j in range(16)] for i in range(rk)]
        new = []
        for row in rows:
            B4 = F([row[4 * i:4 * i + 4] for i in range(4)])
            for x in O4:
                prd = B4 * S[x]
                new.append([int(prd[i, j]) for i in range(4) for j in range(4)])
        rk2 = F(rows + new).rank()
        if rk2 == rk:
            break
        basis = rows + new
    print(f"Route II: dim_F11 algebra generated by the order-4 images = {rk}")


if __name__ == "__main__":
    main()
