#!/usr/bin/env python3
"""
c_sl27.py -- C2 annotation batch, math_B leg, item (c): SL(2,7) facts in the spin thread.

Self-contained.  Builds SL(2,7) from scratch over F_7 (all 2x2 matrices of det 1),
imports no project code, reads no ledger file.

Checks
  1. |SL(2,7)| = 336; histogram of element orders; conjugacy classes (sizes, orders).
  2. Is u = [[1,1],[0,1]] conjugate in SL(2,7) to u^k (k = 1..6)?  Which k occur as
     g u g^-1 = u^k?  Action of s = diag(3,5) and t = diag(4,2) on u; s = -t?
     Does any g in SL(2,7) induce chi: u -> u^3, t -> t on F21 = <u,t>?  Is chi induced
     by conjugation with d = diag(3,1) in GL(2,7) (det 3, a non-square), and does Ad(d)
     swap the classes of u and u^3?
  3. Explicit 4-dim genuine irreps: rho = Ind_B^G(lambda), B = upper-triangular Borel,
     lambda([[a,*],[0,1/a]]) = Legendre(a/7), realised as an 8x8 monomial (+-1) matrix
     rep on the 8 points of P^1(F_7).  Commutant computed exactly (dim 2 => two
     inequivalent irreducible summands); split with the commutant's spectral projectors
     over Q(sqrt(-7)); 4x4 matrices extracted exactly; character norm = 1 exactly;
     sigma(-I) = -Id.
  4. Order-4 elements: count, generated subgroup, linear span of their images in
     sigma4 / sigma4' (exact rank over Q(sqrt(-7)) + numeric SVD), the algebra they
     generate (exact), the algebra generated by one anticommuting pair, clique counts
     for Gamma_x = -i sigma4(x) (pairs / triples / quadruples), omega = G1 G2 G3.
  5. chi_sigma4 o Ad(d) versus chi_sigma4' (outer automorphism swaps the two irreps?).

Exact field: K = Q(r), r^2 = -7, with r identified with +i*sqrt(7) for numerics,
so zeta_QR := zeta + zeta^2 + zeta^4 = (-1 + r)/2 for zeta = exp(2 pi i/7).
"""
import itertools
import sys
from fractions import Fraction as Fr
from collections import Counter, defaultdict

import numpy as np
import sympy as sp

P = 7
QR = {1, 2, 4}


# ---------------------------------------------------------------- group basics
def mul(A, B):
    a, b, c, d = A
    e, f, g, h = B
    return ((a * e + b * g) % P, (a * f + b * h) % P, (c * e + d * g) % P, (c * f + d * h) % P)


def det(A):
    a, b, c, d = A
    return (a * d - b * c) % P


def inv(A):
    a, b, c, d = A
    di = pow(det(A), P - 2, P)
    return ((d * di) % P, (-b * di) % P, (-c * di) % P, (a * di) % P)


I2 = (1, 0, 0, 1)
MINUS_I = (P - 1, 0, 0, P - 1)


def power(A, k):
    R = I2
    for _ in range(k):
        R = mul(R, A)
    return R


def order(A):
    k, R = 1, A
    while R != I2:
        R = mul(R, A)
        k += 1
    return k


def conj(g, x):
    return mul(mul(g, x), inv(g))


def closure(gens):
    S = {I2}
    frontier = [I2]
    while frontier:
        nxt = []
        for x in frontier:
            for g in gens:
                y = mul(x, g)
                if y not in S:
                    S.add(y)
                    nxt.append(y)
        frontier = nxt
    return S


def leg(c):
    c %= P
    if c == 0:
        raise ValueError
    return 1 if c in QR else -1


# ---------------------------------------------------------------- exact field Q(sqrt(-7))
class K:
    __slots__ = ("a", "b")

    def __init__(self, a=0, b=0):
        self.a = Fr(a)
        self.b = Fr(b)

    @staticmethod
    def c(o):
        return o if isinstance(o, K) else K(o, 0)

    def __add__(self, o):
        o = K.c(o)
        return K(self.a + o.a, self.b + o.b)

    __radd__ = __add__

    def __sub__(self, o):
        o = K.c(o)
        return K(self.a - o.a, self.b - o.b)

    def __rsub__(self, o):
        o = K.c(o)
        return K(o.a - self.a, o.b - self.b)

    def __mul__(self, o):
        o = K.c(o)
        return K(self.a * o.a - 7 * self.b * o.b, self.a * o.b + self.b * o.a)

    __rmul__ = __mul__

    def __neg__(self):
        return K(-self.a, -self.b)

    def conjugate(self):
        return K(self.a, -self.b)

    def nrm(self):
        return self.a * self.a + 7 * self.b * self.b

    def inverse(self):
        n = self.nrm()
        return K(self.a / n, -self.b / n)

    def __truediv__(self, o):
        return self * K.c(o).inverse()

    def __eq__(self, o):
        o = K.c(o)
        return self.a == o.a and self.b == o.b

    def __hash__(self):
        return hash((self.a, self.b))

    def iszero(self):
        return self.a == 0 and self.b == 0

    def cplx(self):
        return complex(float(self.a), float(self.b) * 7 ** 0.5)

    def __repr__(self):
        if self.b == 0:
            return f"{self.a}"
        return f"({self.a} + {self.b}*sqrt(-7))"


ZERO, ONE = K(0), K(1)
R7 = K(0, 1)  # sqrt(-7) = +i sqrt 7


def mat_mul(A, B):
    n, m, q = len(A), len(B), len(B[0])
    return [[sum((A[i][k] * B[k][j] for k in range(m)), ZERO) for j in range(q)] for i in range(n)]


def mat_eq(A, B):
    return all(A[i][j] == B[i][j] for i in range(len(A)) for j in range(len(A[0])))


def mat_scalar(A, s):
    return [[x * s for x in row] for row in A]


def mat_add(A, B):
    return [[x + y for x, y in zip(r, s)] for r, s in zip(A, B)]


def ident(n):
    return [[ONE if i == j else ZERO for j in range(n)] for i in range(n)]


def trace(A):
    return sum((A[i][i] for i in range(len(A))), ZERO)


def rref(rows):
    """Exact reduced row echelon form over K. Returns (rref rows (nonzero only), pivots)."""
    M = [list(r) for r in rows]
    nr = len(M)
    nc = len(M[0]) if nr else 0
    rank = 0
    pivots = []
    for col in range(nc):
        piv = None
        for i in range(rank, nr):
            if not M[i][col].iszero():
                piv = i
                break
        if piv is None:
            continue
        M[rank], M[piv] = M[piv], M[rank]
        pv = M[rank][col].inverse()
        M[rank] = [x * pv for x in M[rank]]
        for i in range(nr):
            if i != rank and not M[i][col].iszero():
                f = M[i][col]
                M[i] = [x - f * y for x, y in zip(M[i], M[rank])]
        pivots.append(col)
        rank += 1
    return M[:rank], pivots


def rank_K(rows):
    return len(rref(rows)[0])


def mat_inv(A):
    n = len(A)
    aug = [list(A[i]) + [ONE if i == j else ZERO for j in range(n)] for i in range(n)]
    R, piv = rref(aug)
    assert piv[:n] == list(range(n)), "singular"
    return [row[n:] for row in R]


class Span:
    """Incrementally maintained exact span (RREF basis) for membership tests."""

    def __init__(self, dim):
        self.dim = dim
        self.basis = []  # list of (pivot col, row) in reduced form

    def reduce(self, v):
        v = list(v)
        for pc, row in self.basis:
            if not v[pc].iszero():
                f = v[pc]
                v = [x - f * y for x, y in zip(v, row)]
        return v

    def add(self, v):
        v = self.reduce(v)
        for j, x in enumerate(v):
            if not x.iszero():
                inv_ = x.inverse()
                v = [y * inv_ for y in v]
                # keep basis fully reduced w.r.t. the new pivot
                nb = []
                for pc, row in self.basis:
                    if not row[j].iszero():
                        f = row[j]
                        row = [a - f * b for a, b in zip(row, v)]
                    nb.append((pc, row))
                nb.append((j, v))
                self.basis = nb
                return True
        return False

    def __len__(self):
        return len(self.basis)


def flat(A):
    return [x for row in A for x in row]


def unflat(v, n):
    return [v[i * n:(i + 1) * n] for i in range(n)]


def out(*a):
    print(*a)
    sys.stdout.flush()


# =====================================================================================
def main():
    G = [(a, b, c, d) for a in range(P) for b in range(P) for c in range(P) for d in range(P)
         if (a * d - b * c) % P == 1]
    out("=" * 78)
    out("ITEM (c) -- SL(2,7) facts (math_B leg, independent computation)")
    out("=" * 78)
    out(f"|SL(2,7)| = {len(G)}")
    assert len(G) == 336

    # ---------------- 1. element orders and classes
    ords = {g: order(g) for g in G}
    hist = Counter(ords.values())
    out("Element-order histogram (order: count):", dict(sorted(hist.items())))
    out("Set of element orders:", sorted(hist))
    out("Maximum element order:", max(hist), "| elements of order 24:", hist.get(24, 0))
    out("Divisibility sanity: 336 =", 2 ** 4 * 3 * 7, "; 24 divides 336 but no element has order 24")

    seen = set()
    classes = []
    for g in G:
        if g in seen:
            continue
        cl = {conj(h, g) for h in G}
        seen |= cl
        classes.append(sorted(cl))
    classes.sort(key=lambda c: (ords[c[0]], len(c), c[0]))
    out(f"Number of conjugacy classes: {len(classes)}")
    out("Classes (order, size, a representative):")
    for c in classes:
        out(f"   order {ords[c[0]]:2d}  size {len(c):2d}  rep {c[0]}")
    out("Sorted class sizes:", sorted(len(c) for c in classes))
    cls_of = {}
    for i, c in enumerate(classes):
        for x in c:
            cls_of[x] = i

    # ---------------- 2. u, u^k, s, t, chi
    u = (1, 1, 0, 1)
    t = (4, 0, 0, 2)
    s = (3, 0, 0, 5)
    out("\n--- u = [[1,1],[0,1]] and its powers ---")
    for k in range(1, 7):
        uk = power(u, k)
        conjugators = [g for g in G if conj(g, u) == uk]
        out(f"   u^{k} = {uk}: same SL(2,7)-class as u? {cls_of[uk] == cls_of[u]}; "
            f"#g in SL(2,7) with g u g^-1 = u^{k}: {len(conjugators)}"
            + ("   (k is a QR mod 7)" if k in QR else "   (k is a non-residue mod 7)"))
    ks = sorted({next(k for k in range(1, 7) if power(u, k) == conj(g, u))
                 for g in G if conj(g, u) in {power(u, k) for k in range(1, 7)}})
    out("   {k : g u g^-1 = u^k for some g in SL(2,7)} =", ks)
    NB = [g for g in G if conj(g, u) in {power(u, k) for k in range(7)}]
    out(f"   |N_SL(2,7)(<u>)| = {len(NB)} (all upper triangular: "
        f"{all(g[2] == 0 for g in NB)})")
    out("\n--- s = diag(3,5), t = diag(4,2) ---")
    out(f"   det s = {det(s)}, order(s) = {order(s)}; det t = {det(t)}, order(t) = {order(t)}")
    out(f"   t u t^-1 = {conj(t, u)}  (u^2 = {power(u, 2)})")
    out(f"   s u s^-1 = {conj(s, u)}  (u^2 = {power(u, 2)}, u^3 = {power(u, 3)})")
    out(f"   s == -t ?  {s == mul(MINUS_I, t)};   s^2 == t^2 ?  {mul(s, s) == mul(t, t)}")
    out(f"   s t s^-1 == t ? {conj(s, t) == t}")
    F21 = closure([u, t])
    out(f"   |<u,t>| = {len(F21)} (F21), -I in F21? {MINUS_I in F21}, s in F21? {s in F21}")
    # chi on F21: u -> u^3, t -> t.  Search SL(2,7) for an inducing element.
    hits = [g for g in G if conj(g, u) == power(u, 3) and conj(g, t) == t]
    hits_weak = [g for g in G if conj(g, u) == power(u, 3)]
    out(f"   #g in SL(2,7) with g u g^-1 = u^3 and g t g^-1 = t : {len(hits)}")
    out(f"   #g in SL(2,7) with g u g^-1 = u^3 (any action on t) : {len(hits_weak)}")
    # chi modulo Inn(F21): N_G(F21) and the automorphisms of F21 it induces
    NF = [g for g in G if all(conj(g, x) in F21 for x in (u, t))]
    induced = sorted({next(k for k in range(1, 7) if conj(g, u) == power(u, k)) for g in NF})
    out(f"   |N_SL(2,7)(F21)| = {len(NF)}; induced u -> u^k with k in {induced} "
        f"(Inn(F21) acts on <u> by k in {sorted(QR)})")
    # the outer (diagonal) automorphism Ad(d), d = diag(3,1) in GL(2,7)
    d = (3, 0, 0, 1)
    out(f"   d = diag(3,1): det d = {det(d)} (Legendre {leg(det(d))}: non-square)")
    out(f"   d u d^-1 = {conj(d, u)} (= u^3? {conj(d, u) == power(u, 3)});  d t d^-1 == t? {conj(d, t) == t}")
    Ad_d_ok = all(det(conj(d, g)) == 1 for g in G)
    out(f"   Ad(d) preserves SL(2,7): {Ad_d_ok}")
    swapped = [(i, cls_of[conj(d, c[0])]) for i, c in enumerate(classes) if cls_of[conj(d, c[0])] != i]
    out("   classes moved by Ad(d) (index -> image):", swapped,
        " => Ad(d) is NOT inner (inner automorphisms fix every class)")
    out("   orders of moved classes:", [(ords[classes[i][0]], ords[classes[j][0]]) for i, j in swapped])
    # is Ad(d) composed with any inner automorphism the identity on F21-generators? (i.e. is chi inner?)
    inner_equal = [g for g in G if all(conj(g, x) == conj(d, x) for x in (u, t))]
    out(f"   #g in SL(2,7) with Ad(g) = Ad(d) on F21 : {len(inner_equal)}")

    # ---------------- 3. principal series Ind_B^G(Legendre) as 8x8 monomial matrices
    out("\n--- 8-dim induced rep rho = Ind_B^G(lambda), lambda(diag(a,1/a) n) = (a/7) ---")
    pts = list(range(7)) + ["inf"]

    def act(g, x):
        a, b, c, dd = g
        v1, v2 = (x, 1) if x != "inf" else (1, 0)
        w1, w2 = (a * v1 + b * v2) % P, (c * v1 + dd * v2) % P
        if w2 != 0:
            return (w1 * pow(w2, P - 2, P)) % P, w2  # g v_x = w2 * v_y,  v_y = (y,1)
        return "inf", w1  # g v_x = w1 * (1,0)

    idx = {x: i for i, x in enumerate(pts)}

    def rho_int(g):
        M = np.zeros((8, 8), dtype=np.int64)
        for x in pts:
            y, cc = act(g, x)
            M[idx[y], idx[x]] = leg(cc)
        return M

    RHO = {g: rho_int(g) for g in G}
    # homomorphism on ALL pairs (exact integer check)
    bad = 0
    for g in G:
        Rg = RHO[g]
        for h in G:
            if not np.array_equal(Rg @ RHO[h], RHO[mul(g, h)]):
                bad += 1
    out(f"   homomorphism check over all 336^2 pairs: failures = {bad}")
    out(f"   rho(-I) == -Id_8: {np.array_equal(RHO[MINUS_I], -np.eye(8, dtype=np.int64))}")
    chi8 = {g: int(np.trace(RHO[g])) for g in G}
    norm8 = Fr(sum(chi8[g] ** 2 for g in G), 336)
    out(f"   <chi_rho, chi_rho> = {norm8}  (2 => sum of two inequivalent irreducibles)")
    out("   chi_rho on classes (order:value):", [(ords[c[0]], chi8[c[0]]) for c in classes])

    # commutant (exact, sympy rationals) from generators u and l, then verified on all of G
    l_ = (1, 0, 1, 1)
    out(f"   <u, l> with l = [[1,0],[1,1]] has order {len(closure([u, l_]))}")
    eqs = []
    for g in (u, l_):
        Rg = sp.Matrix(RHO[g].tolist())
        for i in range(8):
            for j in range(8):
                # (X Rg - Rg X)[i,j] = sum_k X[i,k] Rg[k,j] - Rg[i,k] X[k,j]
                row = [0] * 64
                for k in range(8):
                    row[i * 8 + k] += Rg[k, j]
                    row[k * 8 + j] -= Rg[i, k]
                eqs.append(row)
    ns = sp.Matrix(eqs).nullspace()
    out(f"   commutant dimension (exact, from generators u,l): {len(ns)}")
    basis_comm = [sp.Matrix(8, 8, list(v)) for v in ns]
    # choose T not proportional to identity; clear denominators
    T = None
    for Bm in basis_comm:
        if any(Bm[i, j] != 0 for i in range(8) for j in range(8) if i != j) or len(set(Bm[i, i] for i in range(8))) > 1:
            T = Bm
            break
    den = sp.ilcm(*[sp.fraction(x)[1] for x in T])
    T = (T * den).applyfunc(sp.Integer)
    Tn = np.array(T.tolist(), dtype=np.int64)
    comm_all = all(np.array_equal(Tn @ RHO[g], RHO[g] @ Tn) for g in G)
    out(f"   T (integer commutant element) commutes with all 336 rho(g): {comm_all}")
    out("   T =", T.tolist())
    # quadratic relation T^2 = alpha T + beta I
    T2 = T * T
    al, be = sp.symbols("al be")
    sol = sp.solve(list(T2 - al * T - be * sp.eye(8)), [al, be], dict=True)
    al_v, be_v = sol[0][al], sol[0][be]
    disc = al_v ** 2 + 4 * be_v
    out(f"   T^2 = {al_v} T + {be_v} I ; discriminant = {disc} = {sp.factorint(disc) if disc != 0 else 0}")
    # eigenvalues mu = (al +- sqrt(disc))/2 ; express sqrt(disc) = m * sqrt(-7)
    m2 = sp.Rational(disc, -7)
    m = sp.sqrt(m2)
    assert m.is_rational, "discriminant is not -7 * square"
    al_f, m_f = Fr(str(al_v)), Fr(str(m))
    mu1 = K(al_f / 2, m_f / 2)   # (alpha + m sqrt(-7))/2
    mu2 = K(al_f / 2, -m_f / 2)  # (alpha - m sqrt(-7))/2
    out(f"   eigenvalues of T: mu1 = {mu1}, mu2 = {mu2}")

    TK = [[K(int(T[i, j])) for j in range(8)] for i in range(8)]
    Id8 = ident(8)
    P1 = mat_scalar(mat_add(TK, mat_scalar(Id8, -mu2)), (mu1 - mu2).inverse())
    P2 = mat_scalar(mat_add(TK, mat_scalar(Id8, -mu1)), (mu2 - mu1).inverse())
    out(f"   P1^2 == P1: {mat_eq(mat_mul(P1, P1), P1)};  P2^2 == P2: {mat_eq(mat_mul(P2, P2), P2)};  "
        f"P1+P2 == I: {mat_eq(mat_add(P1, P2), Id8)}")
    out(f"   rank P1 = {rank_K(P1)}, rank P2 = {rank_K(P2)}, tr P1 = {trace(P1)}, tr P2 = {trace(P2)}")

    def extract(Pm):
        # basis = independent columns of Pm
        cols = [[Pm[i][j] for i in range(8)] for j in range(8)]
        R, piv = rref([list(r) for r in zip(*cols)])  # rref of Pm (rows) -> pivot columns
        bcols = [cols[j] for j in piv]
        Bm = [[bcols[j][i] for j in range(len(bcols))] for i in range(8)]  # 8 x 4
        # rows where Bm is invertible
        Rt, rpiv = rref([list(r) for r in zip(*Bm)])  # pivots of B^T = independent rows of B
        rows = rpiv
        Bsub_inv = mat_inv([Bm[r] for r in rows])
        return Bm, rows, Bsub_inv

    reps = {}
    for name, Pm in (("A", P1), ("B", P2)):
        Bm, rows, Binv = extract(Pm)
        S = {}
        ok_inv = True
        for g in G:
            RB = [[sum((K(int(RHO[g][i][k])) * Bm[k][j] for k in range(8)), ZERO) for j in range(4)] for i in range(8)]
            Mg = mat_mul(Binv, [RB[r] for r in rows])
            # exact invariance: rho(g) B == B Mg
            if not mat_eq(RB, mat_mul(Bm, Mg)):
                ok_inv = False
            S[g] = Mg
        chi = {g: trace(S[g]) for g in G}
        nrm = sum((chi[g] * chi[g].conjugate() for g in G), ZERO) / 336
        out(f"\n   component {name}: invariance rho(g)B = B sigma(g) for all g: {ok_inv}")
        out(f"   component {name}: sigma(-I) == -Id_4: {mat_eq(S[MINUS_I], mat_scalar(ident(4), K(-1)))}")
        out(f"   component {name}: sigma(I) == Id_4: {mat_eq(S[I2], ident(4))}")
        out(f"   component {name}: <chi,chi> = {nrm}  (exact; 1 => irreducible)")
        out(f"   component {name}: character on classes (order, size, value):")
        for c in classes:
            out(f"        order {ords[c[0]]:2d}  size {len(c):2d}  chi = {chi[c[0]]}")
        reps[name] = (S, chi)

    # Label sigma4 := component with chi(u) = 1 + zeta_QR = (1 + sqrt(-7))/2 (ledger L2518 convention)
    zQR = K(Fr(-1, 2), Fr(1, 2))
    target = ONE + zQR
    names = [n for n in reps if reps[n][1][u] == target]
    assert len(names) == 1
    nA = names[0]
    nB = "B" if nA == "A" else "A"
    sig4, chi4 = reps[nA]
    sig4p, chi4p = reps[nB]
    out(f"\n   sigma4  := component {nA}  (chi(u) = {chi4[u]} = 1 + zeta_QR, zeta_QR = (-1+sqrt(-7))/2)")
    out(f"   sigma4' := component {nB}  (chi(u) = {chi4p[u]})")
    out(f"   chi_sigma4' == conj(chi_sigma4) on all g: {all(chi4p[g] == chi4[g].conjugate() for g in G)}")
    out(f"   chi_sigma4 + chi_sigma4' == chi_rho on all g: {all(chi4[g] + chi4p[g] == K(chi8[g]) for g in G)}")
    # F21 restriction sanity (ledger Part IV: one trivial summand)
    triv_mult = sum((chi4[g] for g in F21), ZERO) / 21
    out(f"   multiplicity of the trivial F21-character in sigma4|F21: {triv_mult}")

    # ---------------- 5. outer automorphism Ad(d) swaps sigma4 <-> sigma4' ; Ad(s) does not
    sw = all(chi4[conj(d, g)] == chi4p[g] for g in G)
    fix_d = all(chi4[conj(d, g)] == chi4[g] for g in G)
    fix_s = all(chi4[conj(s, g)] == chi4[g] for g in G)
    out(f"\n--- twisting by automorphisms ---")
    out(f"   chi_sigma4(d g d^-1) == chi_sigma4'(g) for all g (Ad(d) maps sigma4 to sigma4'): {sw}")
    out(f"   chi_sigma4(d g d^-1) == chi_sigma4(g) for all g: {fix_d}")
    out(f"   chi_sigma4(s g s^-1) == chi_sigma4(g) for all g (Ad(s) inner, fixes sigma4): {fix_s}")

    # ---------------- 4. order-4 elements: span and algebra
    O4 = [g for g in G if ords[g] == 4]
    out(f"\n--- order-4 elements ---")
    out(f"   number of order-4 elements: {len(O4)}; all square to -I: {all(mul(g, g) == MINUS_I for g in O4)}")
    out(f"   one conjugacy class? {len({cls_of[g] for g in O4}) == 1}")
    H = closure(O4)
    out(f"   |subgroup generated by the order-4 elements| = {len(H)}")
    out(f"   closed under inversion; g^-1 == -g for each: {all(inv(g) == mul(MINUS_I, g) for g in O4)}")

    results = {}
    for nm, Srep in (("sigma4", sig4), ("sigma4'", sig4p)):
        vecs = [flat(Srep[g]) for g in O4]
        rk = rank_K(vecs)
        trz = all(trace(Srep[g]).iszero() for g in O4)
        # algebra generated: start from span of images, close under right-mult by generators
        sp_ = Span(16)
        for v in vecs:
            sp_.add(v)
        changed = True
        rounds = 0
        while changed:
            changed = False
            rounds += 1
            current = [unflat(row, 4) for _, row in list(sp_.basis)]
            for Bm in current:
                for g in O4:
                    if sp_.add(flat(mat_mul(Bm, Srep[g]))):
                        changed = True
        alg = len(sp_)
        # numeric cross-check of the span rank
        Mnum = np.array([[x.cplx() for x in v] for v in vecs])
        sv = np.linalg.svd(Mnum, compute_uv=False)
        results[nm] = (rk, alg)
        out(f"   [{nm}] exact rank of span{{sigma(x): x of order 4}} = {rk}   (all traceless: {trz})")
        out(f"   [{nm}] numeric singular values of the 42x16 matrix: "
            + ", ".join(f"{v:.3e}" for v in sv))
        out(f"   [{nm}] exact dimension of the algebra generated by the 42 images = {alg} "
            f"(closure rounds: {rounds})")
        # Gamma = -i sigma(x) spans the same space (scalar multiple) -- note only

    # one anticommuting pair -> algebra dimension; clique census for Gamma_x = -i sigma4(x)
    out("\n--- anticommutation census for Gamma_x = -i sigma4(x) (ledger L2844-L2853 re-check) ---")
    out("   (anticommutation is invariant under the scalar -i, so it is tested on sigma4(x) directly)")

    def anticomm(x, y):
        A, B = sig4[x], sig4[y]
        return mat_eq(mat_add(mat_mul(A, B), mat_mul(B, A)), [[ZERO] * 4 for _ in range(4)])
    ac = {}
    for i, x in enumerate(O4):
        for j in range(i + 1, len(O4)):
            y = O4[j]
            ac[(i, j)] = anticomm(x, y)
    pairs = [k for k, v in ac.items() if v]
    out(f"   anticommuting unordered pairs: {len(pairs)}")
    adj = defaultdict(set)
    for i, j in pairs:
        adj[i].add(j)
        adj[j].add(i)
    triples = [(i, j, k) for (i, j) in pairs for k in adj[i] & adj[j] if k > j]
    out(f"   anticommuting unordered triples: {len(triples)}")
    quads = [(i, j, k, l) for (i, j, k) in triples for l in adj[i] & adj[j] & adj[k] if l > k]
    out(f"   anticommuting unordered quadruples: {len(quads)}")
    # group-level: anticommuting pair <=> x y = -y x in SL(2,7)
    grp_ac = sum(1 for i, x in enumerate(O4) for y in O4[i + 1:] if mul(x, y) == mul(MINUS_I, mul(y, x)))
    out(f"   pairs with x y = -y x in SL(2,7): {grp_ac}")
    Q8s = {frozenset(closure([O4[i], O4[j]])) for i, j in pairs}
    out(f"   distinct subgroups generated by anticommuting pairs: {len(Q8s)}, orders {sorted({len(q) for q in Q8s})}")
    # omega = G1 G2 G3 with G = -i sigma: G1G2G3 = (-i)^3 s1 s2 s3 = i * s1 s2 s3
    scal = Counter()
    for (i, j, k) in triples:
        W = mat_mul(mat_mul(sig4[O4[i]], sig4[O4[j]]), sig4[O4[k]])  # s1 s2 s3 = sigma4(x y z)
        if mat_eq(W, ident(4)):
            scal["G1G2G3 = +i I4"] += 1
        elif mat_eq(W, mat_scalar(ident(4), K(-1))):
            scal["G1G2G3 = -i I4"] += 1
        else:
            scal["non-scalar"] += 1
    out(f"   omega = G1 G2 G3 over the triples (index order): {dict(scal)}")
    # algebra generated by one anticommuting pair
    i, j = pairs[0]
    sp1 = Span(16)
    for g in (O4[i], O4[j]):
        sp1.add(flat(sig4[g]))
    changed = True
    while changed:
        changed = False
        for _, row in list(sp1.basis):
            Bm = unflat(row, 4)
            for g in (O4[i], O4[j]):
                if sp1.add(flat(mat_mul(Bm, sig4[g]))):
                    changed = True
    out(f"   algebra generated by ONE anticommuting pair (one Q8): dimension {len(sp1)}")
    # all six order-4 elements of one Q8, and of two distinct Q8s
    def alg_dim(gens):
        spx = Span(16)
        for g in gens:
            spx.add(flat(sig4[g]))
        changed = True
        while changed:
            changed = False
            for _, row in list(spx.basis):
                Bm = unflat(row, 4)
                for g in gens:
                    if spx.add(flat(mat_mul(Bm, sig4[g]))):
                        changed = True
        return len(spx)

    q8list = sorted(Q8s, key=lambda q: sorted(q))
    q_a, q_b = q8list[0], q8list[1]
    g_a = [x for x in O4 if x in q_a]
    g_b = [x for x in O4 if x in q_b]
    out(f"   algebra generated by the 6 order-4 elements of one Q8: dimension {alg_dim(g_a)}")
    out(f"   algebra generated by the order-4 elements of two distinct Q8s: dimension {alg_dim(g_a + g_b)}"
        f" (they generate a subgroup of order {len(closure(g_a + g_b))})")
    # End(sigma4) = sigma4 (x) sigma4^*: number of irreducible constituents (sum of squared multiplicities)
    m4 = sum(((chi4[g] * chi4[g].conjugate()) * (chi4[g] * chi4[g].conjugate()) for g in G), ZERO) / 336
    m1 = sum((chi4[g] * chi4[g].conjugate() for g in G), ZERO) / 336
    out(f"   End(sigma4): <|chi|^2, |chi|^2> = {m4} (sum of squared multiplicities); "
        f"trivial multiplicity <|chi|^2, 1> = {m1}  => End(sigma4) = scalars + two further irreducibles,"
        f" and the 15-dim span is the full traceless part")

    # sigma4 restricted to 2O = N_SL(2,7)(Q8) (preimage of S4): irreducible = spin-3/2 of 2O?  (supports item m wording)
    out("\n--- sigma4 restricted to 2O (normalizer of a Q8; preimage of an S4 of PSL(2,7)) ---")
    q8 = q8list[0]
    N2O = [g for g in G if all(conj(g, x) in q8 for x in q8)]
    out(f"   |N_SL(2,7)(Q8)| = {len(N2O)}; contains -I: {MINUS_I in N2O}; "
        f"element orders: {dict(sorted(Counter(ords[g] for g in N2O).items()))}")
    nrm2O = sum((chi4[g] * chi4[g].conjugate() for g in N2O), ZERO) / len(N2O)
    out(f"   <chi_sigma4|2O, chi_sigma4|2O> = {nrm2O}  (1 => sigma4|2O irreducible, 4-dim, genuine)")
    # spin-3/2 character of an SU(2) element of order n: eigenvalues exp(+-i theta/2) with theta/2 = 2 pi k/n
    import math
    def chi32(n):
        # SU(2) element of order n has eigenvalues exp(+-2 pi i/n) up to Galois; chi_{3/2} = sum_{m} exp(i m phi), m = 3,1,-1,-3, phi = 2pi/n
        phi = 2 * math.pi / n
        return round(sum(math.cos(m * phi) for m in (3, 1, -1, -3)), 9)
    agree = all(abs(chi4[g].cplx() - chi32(ords[g])) < 1e-9 for g in N2O
                if ords[g] not in (8,)) and all(abs(chi4[g].cplx()) < 1e-12 for g in N2O if ords[g] == 8)
    out(f"   chi_sigma4 on 2O equals the spin-3/2 character (by element order; order-8 values 0): {agree}")

    span_a, alg_a = results["sigma4"]
    span_b, alg_b = results["sigma4'"]
    out("\nSUMMARY (item c)")
    out(f"   element orders of SL(2,7): {sorted(hist)}; order-24 elements: {hist.get(24, 0)}")
    out(f"   u ~ u^k in SL(2,7) exactly for k in {ks}; u^3 is NOT conjugate to u; s u s^-1 = u^2; s = -t")
    out(f"   chi (u->u^3, t->t) is induced by Ad(diag(3,1)), diag(3,1) in GL(2,7) with non-square det;"
        f" no element of SL(2,7) induces it; Ad(diag(3,1)) swaps sigma4<->sigma4': {sw}")
    out(f"   span of the 42 order-4 images: sigma4 {span_a}, sigma4' {span_b} (15 = all traceless 4x4)")
    out(f"   algebra generated by them:     sigma4 {alg_a}, sigma4' {alg_b} (16 = M4(C))")


if __name__ == "__main__":
    main()
