#!/usr/bin/env python3
"""
quotes_check.py -- C2 batch, math_B leg: verify that every ledger quotation used in REPORT.md occurs
verbatim on the stated line of the (read-only) ledger.  Opens the ledger for reading only.
Usage: python3 quotes_check.py /home/claude/fold/SQT_Master_Ledger_v4_93_CANONICAL.md
"""
import hashlib
import sys

QUOTES = [
    # item (c)
    ("c", 20, "lift of χ-involution to SL(2,7) via order-6 inner element s = diag(3, 5)"),
    ("c", 2371, "Lifted to SL(2,7), it is conjugation by s = diag(3, 5), an order-6 inner element."),
    ("c", 2461, "Explicit realization: u = [[1,1],[0,1]] of order 7, t = diag(4, 2) of order 3 with tut⁻¹ = u²."),
    ("c", 2461, "The χ-involution is realized in SL(2,7) by conjugation by s = diag(3, 5), an order-6 inner element with s² = t² ∈ F₂₁."),
    ("c", 2457, "χ_F21(a, b) = (3a mod 7, b) is a genuine group automorphism of F₂₁."),
    ("c", 2494, "Since the χ-involution is realized inside SL(2,7) by conjugation by s ∈ SL(2,7), both σ₄ and σ₄' are individually s-invariant as SL(2,7)-representations. The χ-action *between* σ₄ and σ₄' is visible only at the F₂₁-restriction level, where it swaps the ρ_QR-summand into a ρ_QNR-summand."),
    ("c", 2498, "They are not \"swapped by an outer operator\" in any way that acts internally on either irrep."),
    ("c", 4543, "lifts to inner conjugation by s = diag(3,5) in SL(2,7)"),
    ("c", 2844, "For each of the 42 order-4 elements x ∈ SL(2,7) (all satisfying x² = −I), define Γ_x = −iσ₄(x)."),
    ("c", 2853, "The full algebra generated by the order-4 Γs has complex dimension 4, not 8 (Cℓ(0,3)) or 16 (Cℓ(1,3))."),
    ("c", 2853, "Span dimension check confirms: span{I, Γ₁, Γ₂, Γ₁Γ₂} has complex rank 4 = M₂(ℂ)"),
    ("c", 2857, "(tested on u, t, s, and a random order-24 element)"),
    ("c", 2869, "σ₄ harbors **Cℓ(0,2) ≅ ℍ⊗ℂ** (complexified quaternions, equivalent to the Pauli matrix algebra)."),
    ("c", 2463, "class sizes [1, 1, 24, 24, 24, 24, 42, 42, 42, 56, 56], summing to 336"),
    # item (e)
    ("e", 1782, "The complete graph K₈ admits exactly two non-isomorphic 1-factorizations, which correspond under a natural map to the two orientations of the quadratic residue structure mod 7. The two factorizations are not related by graph automorphism; they are genuinely distinct."),
    # item (f)
    ("f", 1944, "All structurally significant angles in the framework's geometric parameter space cluster in a narrow band between 54° and 60°"),
    ("f", 1950, "| arctan(1/√2) | ≈ 54.74° | Császár K₇ dihedral structure; appears in α⁻¹ (§2.2) |"),
    # item (g)
    ("g", 1792, "The ratio log(4π)/log(7) ≈ 1.286 is **ζ-independent**"),
    # item (l)
    ("l", 408, "α⁻¹ recovers the CODATA value to 0.003% using the formula involving α_bare and the proton radius. This is a retrodiction requiring the experimental muonic proton radius as input. The 1.099% gap between 240/√3 and 137.036 has no structural explanation."),
    ("l", 410, "No calculation currently exists to derive r_p and α_bare simultaneously from the framework's axioms."),
    ("l", 1353, "The α⁻¹ correction formula α⁻¹ = 84/arctan(1/√2) − (correction terms involving the APS boundary) recovers the CODATA value to 0.003% (§2.2 retrodiction)."),
    ("l", 4213, "The quantity arctan(1/√2) imported as \"θ\" was lifted from the α⁻¹_bare formula (§2.25, where it has prior address as a K₇ dihedral)"),
    ("l", 4217, "arctan(1/√2) was imported from the α⁻¹ formula — where 84 was already the numerator — into the E_torus denominator"),
    # item (m)
    ("m", 1045, "The constituent result μ_p = (4μ_u − μ_d)/3 (ratio −3/2, parameter-free, ~3% to data) puts the sign and magnitude of μ_n entirely in the **factor of 4** = the spin-3/2 quartet being a single SU(2) irrep."),
    ("m", 1057, "Supply it and the 4-dim symmetric channel becomes the spin-3/2 quartet, the factor of 4 is **forced**, and μ_n moves from 0 to the −3/2 ratio; fail to and μ_n stays 0."),
    ("m", 1067, "This **unifies** the μ_n factor of 4 with the S⁷/PSL(2,7) η-invariant thread (§G / the Flach problem): they are the same question."),
    ("m", 1077, "**σ₄ |_{2O} = the unique 4-dim genuine irrep of 2O = the spin-3/2** (§2.85) — the factor of 4 is the Cℓ(6) half-spinor as the octahedral subgroup 2O = 2·S₄ ⊂ SL(2,7) sees it"),
    ("m", 1080, "This is a genuine convergence: μ_n's factor of 4 (§2.85), the two genuine 4-dim spin reps of SL(2,7) (§2.77), the coset/crystallization ρ₆ (spectral-rigidity paper), and Furey's Cℓ(6) Standard-Model algebra all turn out to be **one structure** — Spin(6) = SU(4)."),
    ("m", 1084, "so the factor of 4 / spin-3/2 is available and μ_n → −3/2 *on that geometry*."),
    ("m", 4563, "supply −1 ↦ −Id and the factor of 4 is forced, μ_n → −3/2 ratio; otherwise μ_n = 0."),
]


def main(path):
    with open(path, "rb") as fh:
        raw = fh.read()
    print(f"ledger: {path}")
    print(f"md5: {hashlib.md5(raw).hexdigest()}  bytes: {len(raw)}")
    lines = raw.decode("utf-8").split("\n")
    print(f"lines: {len(lines) - (1 if lines and lines[-1] == '' else 0)}")
    bad = 0
    for item, ln, q in QUOTES:
        text = lines[ln - 1]
        ok = q in text
        others = [i + 1 for i, t in enumerate(lines) if q in t and i + 1 != ln]
        bad += not ok
        print(f"[{item}] L{ln}: {'OK ' if ok else 'MISSING'}  also on lines: {others if others else '-'}")
        print(f"      \"{q[:150]}{'...' if len(q) > 150 else ''}\"")
    print(f"\nall quotes verbatim on stated lines: {bad == 0}  (missing: {bad})")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "/home/claude/fold/SQT_Master_Ledger_v4_93_CANONICAL.md")
