#!/usr/bin/env python3
# s2c1_cc_core.py — G-S2C1 CC leg: from-scratch substrate + fluctuation stack (leg 2 of 2).
# ZERO code reuse from the quarantined chat instruments (P-4.b blindness held at build time).
#
# Discretization: Fourier collocation on the p6m primitive cell in lattice coordinates,
# symmetric retained band |m_i| <= n/2 - 1 (Nyquist row/column zeroed); every product is
# evaluated on a 2n zero-padded grid, so the retained-band projection of every operator is
# alias-free and the discrete grand-canonical energy is EXACTLY invariant under continuous
# translations (the discrete Ward identity holds to roundoff by construction).
# Kernel table: U(r) = U0 * exp(-r^8); periodized Fourier coefficients from the continuum
# radial transform Uhat(q) = 2*pi * int_0^Rmax r U(r) J0(qr) dr by 4000-node Gauss-Legendre
# quadrature on [0, RMAX] (direct evaluation at every needed |G+k|; no interpolation table).
# Crystallization: L-BFGS-B direct minimization of the grand-canonical energy at fixed mu,
# then a dense-Newton polish (direct least-squares solve on the full band-basis Hessian),
# with exact p6m symmetrization by integer index maps on the grid.
# Fluctuations: dense Bloch matrices in the Fourier band basis. The form of record is the
# Hermitian one, w2 h = L^{1/2} (L + 2 X) L^{1/2} h, admissible only with
# lambda_min(L) >= -1e-12 verified at every k; the product form w2 f = L (L + 2 X) f is run
# as a cross-check at the two dispatch rungs.
import numpy as np
from numpy.polynomial.legendre import leggauss
from scipy.special import j0

U0 = 20.0          # gem8 kernel amplitude (g*)
A_STAR = 1.46059   # p6m lattice constant
MU = 53.225        # fixed chemical potential (E-3 tuple)
RMAX = 2.0         # kernel support cutoff: U0*exp(-2^8) ~ 1e-110, fully negligible
NGL = 4000         # Gauss-Legendre nodes for the radial kernel transform

_gl_cache = None


def uhat_radial(q):
    """Continuum 2-D radial Fourier transform of U at radii q (array), by GL quadrature."""
    global _gl_cache
    if _gl_cache is None:
        x, w = leggauss(NGL)
        r = 0.5 * RMAX * (x + 1.0)
        wt = 0.5 * RMAX * w * r * (U0 * np.exp(-r ** 8)) * 2.0 * np.pi
        _gl_cache = (r, wt)
    r, wt = _gl_cache
    q = np.asarray(q, dtype=float)
    flat = q.ravel()
    out = np.empty(flat.shape)
    step = max(1, 200000 // NGL)
    for i in range(0, flat.size, step):
        out[i:i + step] = j0(np.outer(flat[i:i + step], r)) @ wt
    return out.reshape(q.shape)


class Cell:
    """Geometry + spectral machinery for one resolution n (grid n x n, padded 2n x 2n)."""

    def __init__(self, n):
        self.n = n
        self.N = 2 * n
        a = A_STAR
        self.A1 = np.array([a, 0.0])
        self.A2 = np.array([0.5 * a, 0.5 * np.sqrt(3.0) * a])
        M = np.array([self.A1, self.A2])
        self.area = abs(np.linalg.det(M))
        K = 2.0 * np.pi * np.linalg.inv(M).T
        self.B1, self.B2 = K[0], K[1]
        assert abs(self.B1 @ self.A1 - 2 * np.pi) < 1e-12 and abs(self.B1 @ self.A2) < 1e-12
        # retained-band integer indices on the n-grid (numpy fft layout)
        m = np.fft.fftfreq(n, 1.0 / n).astype(int)
        self.M1 = m[:, None] + np.zeros(n, int)[None, :]
        self.M2 = np.zeros(n, int)[:, None] + m[None, :]
        self.band = (np.abs(self.M1) <= n // 2 - 1) & (np.abs(self.M2) <= n // 2 - 1)
        self.Gx = self.M1 * self.B1[0] + self.M2 * self.B2[0]
        self.Gy = self.M1 * self.B1[1] + self.M2 * self.B2[1]
        self.G2 = self.Gx ** 2 + self.Gy ** 2
        # padded-grid integer indices / wavevectors
        N = self.N
        mp = np.fft.fftfreq(N, 1.0 / N).astype(int)
        self.P1 = mp[:, None] + np.zeros(N, int)[None, :]
        self.P2 = np.zeros(N, int)[:, None] + mp[None, :]
        self.GxP = self.P1 * self.B1[0] + self.P2 * self.B2[0]
        self.GyP = self.P1 * self.B1[1] + self.P2 * self.B2[1]
        self.UhatP = uhat_radial(np.sqrt(self.GxP ** 2 + self.GyP ** 2))
        # real-space sample points r = s1 A1 + s2 A2, s_i = i/n
        s = np.arange(n) / n
        self.rx = s[:, None] * self.A1[0] + s[None, :] * self.A2[0]
        self.ry = s[:, None] * self.A1[1] + s[None, :] * self.A2[1]
        # p6m point-group index maps (order 12), generated by the C6 rotation
        # h(i,j) = f((i+j) mod n, -i mod n) and the bond mirror h(i,j) = f((i+j) mod n, -j mod n)
        I, J = np.meshgrid(np.arange(n), np.arange(n), indexing="ij")
        maps, seen = [], set()
        frontier = [(I, J)]
        gens = [lambda i, j: ((i + j) % n, (-i) % n), lambda i, j: ((i + j) % n, (-j) % n)]
        while frontier:
            cur = frontier.pop()
            key = (cur[0].tobytes(), cur[1].tobytes())
            if key in seen:
                continue
            seen.add(key)
            maps.append(cur)
            for g in gens:
                frontier.append(g(cur[0], cur[1]))
        assert len(maps) == 12, "p6m point group closure gave %d maps" % len(maps)
        self.symmaps = maps

    # -- spectral helpers (coefficients c in numpy fft layout; y = ifft2(c)*n^2) --
    def coeff(self, y):
        return (np.fft.fft2(y) / self.n ** 2) * self.band

    def grid(self, c):
        return np.fft.ifft2(c) * self.n ** 2

    def pad(self, c):
        n, N = self.n, self.N
        Cs = np.fft.fftshift(c)
        P = np.zeros((N, N), complex)
        P[N // 2 - n // 2:N // 2 + n // 2, N // 2 - n // 2:N // 2 + n // 2] = Cs
        return np.fft.ifftshift(P)

    def trunc(self, P):
        n, N = self.n, self.N
        Ps = np.fft.fftshift(P)
        Cs = Ps[N // 2 - n // 2:N // 2 + n // 2, N // 2 - n // 2:N // 2 + n // 2]
        return np.fft.ifftshift(Cs)

    def padded_grid(self, c):
        return np.fft.ifft2(self.pad(c)) * self.N ** 2

    def symmetrize(self, y):
        acc = np.zeros_like(y)
        for (I, J) in self.symmaps:
            acc += y[I, J]
        return acc / len(self.symmaps)

    # -- energy / stationarity --
    def rho_hat_padded(self, c):
        psip = self.padded_grid(c).real
        return np.fft.fft2(psip * psip) / self.N ** 2, psip

    def energy_grad(self, y):
        """Grand-canonical energy per cell and its gradient wrt the n x n grid values."""
        n, N, A = self.n, self.N, self.area
        c = self.coeff(y)
        rho_hat, psip = self.rho_hat_padded(c)
        Vp_hat = self.UhatP * rho_hat
        E_int = 0.5 * A * float(np.sum(self.UhatP * np.abs(rho_hat) ** 2))
        E_kin = A * float(np.sum(0.5 * self.G2 * np.abs(c) ** 2))
        E_mu = -MU * A * float(np.sum(np.abs(c) ** 2))
        Vp = np.fft.ifft2(Vp_hat).real * N ** 2
        gp = (2.0 * A / N ** 2) * psip * Vp
        g_int = np.fft.ifft2(self.band * self.trunc(np.fft.fft2(gp))).real
        g_kin = np.fft.ifft2(self.band * (2.0 * A * (0.5 * self.G2 - MU)) * c).real
        return E_kin + E_mu + E_int, g_int + g_kin

    def L_coeff(self, c):
        """Band projection of L psi, L = -1/2 lap - mu + U*rho0, as coefficients."""
        rho_hat, psip = self.rho_hat_padded(c)
        Vp = np.fft.ifft2(self.UhatP * rho_hat).real * self.N ** 2
        Lp_hat = np.fft.fft2(Vp * psip) / self.N ** 2
        return (0.5 * self.G2 - MU) * c + self.band * self.trunc(Lp_hat)

    def residual_rel(self, c):
        Lc = self.L_coeff(c)
        return float(np.linalg.norm(Lc) / np.linalg.norm(c)), Lc


class Fluct:
    """Dense Bloch fluctuation matrices in the Fourier band basis for one crystal state."""

    def __init__(self, cell, c_psi):
        self.cell = cell
        n, N = cell.n, cell.N
        sel = np.where(cell.band.ravel())[0]
        self.sel = sel
        self.d = sel.size
        self.mb1 = cell.M1.ravel()[sel]
        self.mb2 = cell.M2.ravel()[sel]
        self.kvx = self.mb1 * cell.B1[0] + self.mb2 * cell.B2[0]
        self.kvy = self.mb1 * cell.B1[1] + self.mb2 * cell.B2[1]
        # product-space rows |K_i| <= n-2 (psi0*f has exactly this band)
        r = np.arange(-(n - 2), n - 1)
        K1 = (r[:, None] + np.zeros(r.size, int)[None, :]).ravel()
        K2 = (np.zeros(r.size, int)[:, None] + r[None, :]).ravel()
        self.K1, self.K2 = K1, K2
        self.Kx = K1 * cell.B1[0] + K2 * cell.B2[0]
        self.Ky = K1 * cell.B1[1] + K2 * cell.B2[1]
        psihatP = cell.pad(c_psi)
        self.Cpsi = psihatP[(K1[:, None] - self.mb1[None, :]) % N,
                            (K2[:, None] - self.mb2[None, :]) % N]
        # local potential V = U*rho0 (exact band <= n-2) as a convolution matrix
        rho_hat, _ = cell.rho_hat_padded(c_psi)
        Vhat = cell.UhatP * rho_hat
        self.CV = Vhat[(self.mb1[:, None] - self.mb1[None, :]) % N,
                       (self.mb2[:, None] - self.mb2[None, :]) % N]
        self.CV = 0.5 * (self.CV + self.CV.conj().T)

    def matrices(self, kx, ky):
        """Return (L, X) at Bloch vector k; both exactly Hermitian (symmetrized, asym recorded)."""
        kin = 0.5 * ((self.kvx + kx) ** 2 + (self.kvy + ky) ** 2)
        L = np.diag(kin - MU) + self.CV
        D = uhat_radial(np.sqrt((self.Kx + kx) ** 2 + (self.Ky + ky) ** 2))
        X = self.Cpsi.conj().T @ (D[:, None] * self.Cpsi)
        asym = float(np.linalg.norm(X - X.conj().T) / max(np.linalg.norm(X), 1e-300))
        X = 0.5 * (X + X.conj().T)
        return L, X, asym

    def hermitian_spectrum(self, kx, ky, nlow=6):
        """Hermitian form of record: w2 h = L^{1/2}(L+2X)L^{1/2} h. Returns diagnostics."""
        L, X, asym = self.matrices(kx, ky)
        lam, W = np.linalg.eigh(L)
        lam_min = float(lam[0])
        S = (W * np.sqrt(np.clip(lam, 0.0, None))) @ W.conj().T
        A2X = L + 2.0 * X
        Mh = S @ A2X @ S
        Mh = 0.5 * (Mh + Mh.conj().T)
        w2, H = np.linalg.eigh(Mh)
        order = np.argsort(np.abs(w2))
        idx = order[:nlow]
        modes = []
        for i in idx:
            h = H[:, i]
            f = S @ h
            modes.append((float(w2[i]), f))
        modes.sort(key=lambda t: abs(t[0]))
        return {"lambda_min_L": lam_min, "asym_X": asym, "modes": modes,
                "w2_all_low": sorted([float(w2[i]) for i in idx])}

    def product_w2(self, kx, ky, nlow=8):
        """Product-form cross-check: eigenvalues of L(L+2X), lowest nlow by |w2|."""
        L, X, _ = self.matrices(kx, ky)
        w2 = np.linalg.eigvals(L @ (L + 2.0 * X))
        w2 = w2[np.argsort(np.abs(w2))][:nlow]
        return w2


def mode_character(cell, c_psi, f_coeff_vec, fl, kx, ky):
    """Classify one fluctuation mode: density part delta-rho = psi0*f, regressed on
    {rho0, dx rho0, dy rho0} (mutually orthogonal on the cell); returns R2, grad share,
    E2 (traceless-strain) fraction o2 from the recovered displacement polarization."""
    n = cell.n
    C = np.zeros((n, n), complex)
    C.ravel()[fl.sel] = f_coeff_vec
    fp = np.fft.ifft2(cell.pad(C)) * cell.N ** 2
    psip = cell.padded_grid(c_psi).real
    drho = psip * fp
    rho_hat, _ = cell.rho_hat_padded(c_psi)
    rho0 = np.fft.ifft2(rho_hat).real * cell.N ** 2
    dxr = np.fft.ifft2(1j * cell.GxP * rho_hat).real * cell.N ** 2
    dyr = np.fft.ifft2(1j * cell.GyP * rho_hat).real * cell.N ** 2
    B = np.stack([rho0.ravel(), dxr.ravel(), dyr.ravel()], axis=1)
    coef, res, _, _ = np.linalg.lstsq(B, drho.ravel(), rcond=None)
    fit = B @ coef
    tot = float(np.sum(np.abs(drho) ** 2))
    rr = float(np.sum(np.abs(drho.ravel() - fit) ** 2))
    R2 = 1.0 - rr / max(tot, 1e-300)
    p_rho = float(np.abs(coef[0]) ** 2 * np.sum(rho0 ** 2))
    p_grad = float(np.sum(np.abs(fit - coef[0] * rho0.ravel()) ** 2))
    grad_share = p_grad / max(p_rho + p_grad, 1e-300)
    eps = -coef[1:3]  # displacement polarization from delta-rho = -(ik.eps) rho0 - eps.grad rho0
    k = np.array([kx, ky])
    e = 0.5 * (np.outer(k, eps) + np.outer(eps, k))
    tr = np.trace(e)
    dev = e - 0.5 * tr * np.eye(2)
    ne = float(np.sum(np.abs(e) ** 2))
    o2 = float(np.sum(np.abs(dev) ** 2) / max(ne, 1e-300))
    return {"R2": R2, "grad_share": grad_share, "o2": o2,
            "alpha": [float(coef[0].real), float(coef[0].imag)],
            "eps": [[float(eps[0].real), float(eps[0].imag)],
                    [float(eps[1].real), float(eps[1].imag)]]}


def crystallize(cell, lbfgs_maxiter=8000, newton_iters=12, target=1e-11):
    """Own-solver crystallization at fixed mu: L-BFGS-B + dense-Newton polish + p6m symmetrization.
    Seed: periodized single Gaussian peak on a positive offset (own seed family)."""
    from scipy.optimize import minimize
    n = cell.n
    d2 = None
    for i in (-1, 0, 1):
        for jj in (-1, 0, 1):
            dx = cell.rx - (i * cell.A1[0] + jj * cell.A2[0])
            dy = cell.ry - (i * cell.A1[1] + jj * cell.A2[1])
            dd = dx ** 2 + dy ** 2
            d2 = dd if d2 is None else np.minimum(d2, dd)
    y = 0.55 + 0.9 * np.exp(-d2 / (2 * 0.45 ** 2))
    y *= np.sqrt(0.93 / np.mean(y ** 2))
    y = cell.symmetrize(y)

    def fun(z):
        E, g = cell.energy_grad(z.reshape(n, n))
        return E, g.ravel()

    r0 = minimize(fun, y.ravel(), jac=True, method="L-BFGS-B",
                  options={"maxiter": lbfgs_maxiter, "ftol": 1e-18, "gtol": 1e-10, "maxcor": 30})
    y = cell.symmetrize(r0.x.reshape(n, n))
    c = cell.coeff(y)
    hist = [("lbfgs", int(r0.nit), cell.residual_rel(c)[0])]
    for it in range(newton_iters):
        res, Lc = cell.residual_rel(c)
        if res <= target:
            break
        fl = Fluct(cell, c)
        L, X, _ = fl.matrices(0.0, 0.0)
        H = L + 2.0 * X
        rhs = -Lc.ravel()[fl.sel]
        dc, *_ = np.linalg.lstsq(H, rhs, rcond=1e-9)
        step = 1.0
        for _ in range(8):
            Ct = c.copy()
            Ct.ravel()[fl.sel] += step * dc
            yt = cell.symmetrize(cell.grid(Ct).real)
            ct = cell.coeff(yt)
            if cell.residual_rel(ct)[0] < res:
                c = ct
                break
            step *= 0.5
        else:
            break
        hist.append(("newton", it + 1, cell.residual_rel(c)[0]))
    res, _ = cell.residual_rel(c)
    return c, res, hist


def prolong(cell_from, cell_to, c):
    """Embed band coefficients of a coarse cell into a finer cell (seed for re-crystallization)."""
    nf, nt = cell_from.n, cell_to.n
    Cs = np.fft.fftshift(c)
    P = np.zeros((nt, nt), complex)
    P[nt // 2 - nf // 2:nt // 2 + nf // 2, nt // 2 - nf // 2:nt // 2 + nf // 2] = Cs
    return np.fft.ifftshift(P) * cell_to.band


def crystallize_from_seed(cell, c_seed, newton_iters=12, target=1e-11, lbfgs_maxiter=2000):
    from scipy.optimize import minimize
    n = cell.n
    y = cell.symmetrize(cell.grid(c_seed).real)

    def fun(z):
        E, g = cell.energy_grad(z.reshape(n, n))
        return E, g.ravel()

    r0 = minimize(fun, y.ravel(), jac=True, method="L-BFGS-B",
                  options={"maxiter": lbfgs_maxiter, "ftol": 1e-18, "gtol": 1e-10, "maxcor": 30})
    y = cell.symmetrize(r0.x.reshape(n, n))
    c = cell.coeff(y)
    hist = [("lbfgs", int(r0.nit), cell.residual_rel(c)[0])]
    for it in range(newton_iters):
        res, Lc = cell.residual_rel(c)
        if res <= target:
            break
        fl = Fluct(cell, c)
        L, X, _ = fl.matrices(0.0, 0.0)
        H = L + 2.0 * X
        rhs = -Lc.ravel()[fl.sel]
        dc, *_ = np.linalg.lstsq(H, rhs, rcond=1e-9)
        step = 1.0
        for _ in range(8):
            Ct = c.copy()
            Ct.ravel()[fl.sel] += step * dc
            yt = cell.symmetrize(cell.grid(Ct).real)
            ct = cell.coeff(yt)
            if cell.residual_rel(ct)[0] < res:
                c = ct
                break
            step *= 0.5
        else:
            break
        hist.append(("newton", it + 1, cell.residual_rel(c)[0]))
    res, _ = cell.residual_rel(c)
    return c, res, hist


def direction_unit(tag):
    if tag == "GK":       # along a bond (the a1 / x direction)
        return np.array([1.0, 0.0])
    if tag == "GM":       # 30 degrees
        return np.array([np.sqrt(3.0) / 2.0, 0.5])
    raise ValueError(tag)


LADDER_KA = sorted(set([0.3 / 2 ** j for j in range(9)] + [0.005, 0.01, 0.015, 0.02, 0.03]))
