#!/usr/bin/env python3
"""foldin_v4_81_gs2c1w.py — STAGES V4.81: Gate G-S2C1-W (the W_∪′ re-derivation mini-gate) CLOSED two-leg: INERT, OOM-ROBUST.
Seven additive edits on SQT_Master_Ledger_v4_80_CANONICAL.md (md5 a28e9b40...):
  E1 title; E2 As-of prepend (accumulated); E3 V4.81 fold-in record (before V4.80); E4 additive V4.81 bracket on the §2.91.O
  PF-S2 sentence; E5 additive V4.81 annotation on the Part VI G-POLY1 window row; E6 one Part VI gate row (after the G-S2C1 row);
  E7 one changelog line. No new §2.x paragraph: the gate re-derives a window it leaves unchanged.
§2.52 Open 3 untouched — the unique Part VI row asserted byte-identical pre/post, in addition to the reverse-splice.
Anchors asserted unique; reverse-splice reconstructs V4.80 byte-identically before the candidate is accepted."""
import hashlib, os

SRC = os.environ.get("V480", "/home/claude/SQT_Master_Ledger_v4_80_CANONICAL.md")
OUT = os.environ.get("V481", "/home/claude/SQT_Master_Ledger_v4_81_CANDIDATE.md")
V480 = "a28e9b40616ee9b5798e9a5be027c1d9"; V480_BYTES = 1514144

s = open(SRC, encoding="utf-8").read()
assert hashlib.md5(s.encode("utf-8")).hexdigest() == V480 and len(s.encode("utf-8")) == V480_BYTES, "base V4.80 mismatch — halt"
L = s.split("\n")
def uniq_line(prefix):
    hits = [l for l in L if l.startswith(prefix)]; assert len(hits) == 1 and s.count(hits[0]) == 1, prefix; return hits[0]
LINE_O    = uniq_line("**O. Gate G-S2C1 REGISTERED")
ROW_POLY  = uniq_line("| **Gate G-POLY1**")
ROW_S2C1  = uniq_line("| **Gate G-S2C1**")
LINE_CH80 = uniq_line("*V4.80 (September 6, 2026)")
O3_PRE    = uniq_line("| **§2.52 Open 3**")
assert ROW_POLY.endswith(" |") and ROW_S2C1.endswith(" |")

# E1 title
T_OLD, T_NEW = "# SQT Master Ledger — V4.80 Canonical\n", "# SQT Master Ledger — V4.81 Canonical\n"
assert s.count(T_OLD) == 1
# E2 As-of prepend (accumulated)
A_OLD = "**As of:** September 6, 2026 (V4.80 fold — "
A_SUM = ("**As of:** September 9, 2026 (V4.81 fold — **GATE G-S2C1-W (the W_∪′ re-derivation mini-gate, the PF-S2 successor) CLOSED two-leg: INERT, OOM-ROBUST — with the S2 channel's measured O(k²) dispersion at both scales made into constraint curves, the single sealed dispersion budget is non-binding on the domain scale by ~5 orders of magnitude; W_∪′ = W_∪ = (0, 2.1213132100130068 m] on the governing arm hex:step; W_∪ REMAINS SUSPENDED; W_∪′ BANKED ALONGSIDE it (E-W-7(a)); NO reinstatement.** "
"Lattice floor F_L = c_q·|a₂^L|·(k·a_phys)² ≈ 10⁻⁸¹ under the declared chain (ξ = ℓ_P, C = ξ/a ∈ [0.0213, 0.0851] ⇒ a_phys ∈ [1.899, 7.588]×10⁻³⁴ m) — VOID-TRIVIAL exactly as registered pre-data; FAIL-L never fired under any reading (Γ–K/Γ–M × a_phys.lo/hi, ×10 relaxation). Grain-scale Born `disp` edges 1.5–2.2×10⁵ m (kd 0.13–0.19, inside the 0.3 envelope; one DRESSING-SENSITIVE flag on hex:step, Δ₄ 0.138, non-governing); under ×10 the edges leave the envelope (VOID — widens only), under ×0.1 they stay non-governing: gate class INERT under all three scalings on both legs. "
"Cycle: G-POLY1 Phase-3 machinery recovered from claude/new-session-e1u91p @ dd813646 (14 files, MANIFEST 13/13, every ledger hash matched) and asserted in-repo by the CC leg; staging memo 1ebb6a82 LOCKED September 8 with E-W-1..7 (declared a_phys chain; Γ–K window / Γ–M robustness arm; each leg its own a₂ column; author-supplied sealed file; CC-blind-first; Born edge of record; banked alongside) and D-W-1/4/5/6/7 ratified; T1 20ba1e7e (34 patterns) ∪ A1 735eae30 (author, 4) = 37; pinned inputs d1edc69b author-verified; sealed anchor file 8c7d59f6 (one `disp` row, q = group, identifiers masked everywhere); dispatch 7ca7e9e9 (13 embeds, P-4/P-4.b/P-4.c, delivered alone — clean at CC). Two-leg: chat v6.1 e034d428 post-exposure read #2 (af7516c5; read #1 X-1 masking self-scan fired fail-closed, H-W-4); CC from scratch cd9c21dc on claude/new-session-q8iuz5 (6dde4ae6; report 835c478f; manifest 5/5), blind read of record, embed #8 never decoded; comparator v1.1p 55e6977e (v1.1 f27a008f + identity-anchor re-pin) run 3: 105 items, zero deviation on every verdict-bearing quantity, C-W-7 independence witness PASS (CC F_L = chat × 1.034860 exactly, E-W-3(a) honored), 19 representational/definitional misses disclosed (H-W-6 conceded chat-side, reconciled 1f8451e8 without re-read). "
"An S9 on a prior 'CC checkpoint' supplied as text (722f0f1d ≠ declared 97f26c04): all 49 numeric leaves bit-identical to the chat leg including the F_L that E-W-3(a) forces to differ — the independence witness FAILED; superseded by the return of record; comparator v1.1 (C-W-0 provenance + C-W-7 witness) frozen before the re-emission (H-W-5); standing amendment P-5 (independence witness for every difference-forcing election) PROPOSED for election. Chat blindness on the `disp` set burned at delivery (sealed row arrived in the clear — H-W-2; CC read is the read of record for the class). Q-W-1 recorded (the sealed wavenumber vs the named source's own radiation wavenumber; sealed text dispositive; INERT a fortiori at the lower k). No observable, no bridge, no channel-speed-equality claim, no μ_n; §2.52 Open 3 untouched. Full V4.81 record below. V4.80 fold (September 6, 2026) — ")
assert s.count(A_OLD) == 1
# E3 V4.81 fold-in record
R_ANCH = "**V4.80 fold-in record (September 6, 2026):**"
RECORD = ("**V4.81 fold-in record (September 9, 2026):** GATE FOLD, Cluster CI successors, author-authorized (directive verbatim to be filed as `FOLD_AUTHORIZATION_V4_81.md`; staged-candidate hash reported back for final authorization) — **Gate G-S2C1-W CLOSED two-leg INERT, OOM-ROBUST; W_∪′ = W_∪ banked alongside the suspended W_∪; no reinstatement; no new §2.x paragraph (the gate re-derives a window it leaves unchanged).** "
"Lock chain: staging memo 1ebb6a82 (32,219 B) LOCKED September 8, 2026 — operational definition of W_∪′ (§3: dispersion law δ = a₂^agg(kd)² + a₂^L(k·a_phys)² with the lattice term a FLOOR consuming budget; new anchor kind `disp`; Born edge √(B′/c_q|a₂^agg|)/k; envelope VOID at kd > 0.3; a₄ dressing diagnostic; G-POLY1 edges carried as PINNED numbers from the blind-leg checkpoint 2064bd7b, the G-POLY1 sealed file NOT re-opened; union CONSERVATIVE; comparison LAST → TIGHTENED / INERT / FAIL-L; INERT ≠ reinstatement); lock record 5f963ed8 (E-W-1 (a) declared chain ξ = ℓ_P + G-C1 C-interval; E-W-2 (a) Γ–K window / Γ–M robustness; E-W-3 (a) each leg its own a₂, CI in comparator; E-W-4 (i) author-supplied sealed file, T1 frozen without the D-W-2 merge; E-W-5 (a) CC-BLIND-FIRST; E-W-6 (a) Born a₂-only edge of record, dressed reported; E-W-7 (a) banked alongside, no reinstatement; defaults D-W-1/4/5/6/7 ratified; import delta zero); T1 20ba1e7e (34 pattern lines: 11 base recovered byte-exact from mapper v5 2c5ca7a4, 21 identifier-class, 2 G-POLY1 ledger-disclosed reference strings; scanner of record ccd47ac5 implementing the D-W-7 contextual numeric rule); T1-A1 735eae30 (author, 4 lines); pinned inputs d1edc69b (5,769 B; a₂ both legs both directions; a₂^agg / a₄^agg quartets; Q_T, s₁; the four G-POLY1 edges read programmatically from 2064bd7b; ℓ_P = 1.616255×10⁻³⁵ m (CODATA 2018); a_phys interval; all constants) AUTHOR-VERIFIED; Addendum 1 12580917 (sealed 8c7d59f6 154 B, census 1 row / {disp: 1} / 8 fields machine-confirmed; declared external CC md5 97f26c04; H-W-2, D-W-8/9/10, Q-W-1); Addendum 2 7cdcf7e6 (CC return of record; S9-R1 path (a) executed; identity-anchor re-pin 97f26c04 → 6dde4ae6; run 3; H-W-6 concession; closure conditional on the author's word; P-5 proposed). "
"Chat leg: instrument v6 044fc22e (T1 self-grep at every invocation; F-W-PIN 1e-12 with the G-POLY1 edges pinned byte-exact from 2064bd7b; sealed single open with md5 + census + separator guard, NAMED-KEY binder for `B =` / `k = … /m`; masked X-1 abort; suites S4–S13 on synthetic values disjoint from the sealed file; comparison-last gate; F-W-MONO trap) — read #1 X-1 (the masking self-scan fired on the multi-token A1 patterns; fail-closed, nothing leaked, H-W-4); v6.1 e034d428 (two-pass masker + S13b) read #2 of record af7516c5 (18,857 B): per-arm F_L 1.017×10⁻⁸¹ (Γ–K, a_phys.lo; robustness 1.6–2.5×10⁻⁸⁰), Born disp edges 2.224×10⁵ / 1.871×10⁵ / 1.783×10⁵ / 1.512×10⁵ m (hex:step / hex:gem8 / cubic:step / cubic:gem8), kd 0.191 / 0.160 / 0.153 / 0.130, dressed 2.434×10⁵ / 1.983×10⁵ / 1.877×10⁵ / 1.566×10⁵ m, Δ₄ 0.138 (DRESSING-SENSITIVE) / 0.098 / 0.087 / 0.063; per-arm W′ upper = the pinned G-POLY1 edge on every arm (2.1213132100130068 / 1.8866794048346085 / 1.838266105289967 / 1.6447865351995365 m), classes P-2′; W_∪′ = (0, 2.1213132100130068] (hex:step), intersection upper 1.6447865351995365 m; pre-comparison md5 7aa03439; comparison INERT, ratio 1.0 exactly, OOM-ROBUST at gate level; T1 checkpoint scan 0 hits / 17 logged numeric collisions (the parsed budget and wavenumber as JSON numbers). Dispatch G_S2C1_W_CC_DISPATCH_INBAND.md 7ca7e9e9 (115,183 B; 13 embeds; sealed file, T1-A1 and the chat instrument base64-armored; pinned inputs armored for byte-exactness; extractor 5ebf4085 embedded and re-extraction-verified in a clean directory; machinery referenced by commit + MANIFEST rather than re-shipped). "
"CC leg (branch claude/new-session-q8iuz5; checkpoint commit 4184c2ab, report + manifest commit 208902e0; report 835c478f; manifest c827f1d6 5/5): dispatch verified ALONE (P-4.c clean), 13/13 embeds, machinery asserted in-repo at dd813646, own scanner 6fd00b1b (37 patterns, 0 hits), F-W-PIN 46/46, mapper cd9c21dc from scratch (own lexer with NAMED-KEY binder and band support, own Born edge, own fixed-point dressing with turnover guard + bisection fallback, own union, own comparison-last gate; CC-DD-1..7), 24/24 pre-read suites (dc707df5), invocation 1 aborted masked CENSUS pre-parse on the sealed row's inline-code backticks — read NOT spent; unwrap added on structure-only evidence (CC-DD-3 / H-CC-2); invocation 2 the single spent read: F_L 1.052×10⁻⁸¹ (the CC a₂ column — E-W-3(a) honored), edges and classes identical to the chat leg, INERT, gate-level OOM-ROBUST; per-arm oom_robust false (rule-faithful: under ×10 the arm label flips P-2′ → VOID-DISP with the window invariant); H-CC-1 (a blind pre-read synthetic numerically equal to the sealed budget; verdict-inert; disclosed, not re-cut); embed #8 never decoded. "
"Two-leg record: comparator v1.0 007688e5 + schema dd014b8c FROZEN pre-chat-emission (D-W-9: CC's first run preceded the dispatch); run 1 OUTSTANDING (no CC file); run 2 on a 'CC checkpoint' supplied as text (722f0f1d ≠ declared 97f26c04): S9 FIRED on a suspicious PASS — all 49 numeric leaves bit-identical to the chat checkpoint including F_L, which E-W-3(a) forces to differ by ×1.034860; placeholder instrument_md5 / pre_comparison_md5; the counter-cross-check protocol operating in its intended direction (D-W-11/12/13); comparator v1.1 f27a008f + schema v1.1 6c020e94 FROZEN before any re-emission (C-W-0 provenance: real md5s, recomputable comparison-last hash, required keys; C-W-7 independence witness on F_L; H-W-5); v1.1p 55e6977e (identity-anchor re-pin only) run 3 of record vs the return: 105 items, ZERO deviation on every verdict-bearing quantity, C-W-7 PASS on all arms, 19 misses — 15 representational (census structure, index base, governing-label and reinstatement strings, keys filed elsewhere, the pre-comparison record definition post-dating the dispatch) + 4 definitional (per-arm oom_robust; H-W-6 conceded chat-side, memo-letter reconciliation 1f8451e8 from the chat checkpoint's own serialized OOM records → false on all arms = CC; window invariant). "
"Honesty ledger (chat): H-W-0 (recovery), H-W-1 (scanner glue rule; decoy collision logged, list not re-cut), H-W-2 (chat blindness burned at delivery — sealed row in the clear), H-W-3 (suite synthetics mis-sized, pre-read), H-W-4 (token-level masker vs multi-token patterns; X-1 fail-closed), H-W-5 (comparator lacked an independence witness), H-W-6 (per-arm OOM criterion). Deviations D-W-0 (G-POLY1 anchors ledger-disclosed), D-W-1 (lost chat estate pinned from V4.80 + 2064bd7b), D-W-2 (T1 lists 8cd89b9a / 653a0b74 not merged — by election), D-W-3 (lattice CI 3.5%; a₄^L excluded), D-W-4 (new kind suites), D-W-5 (inherited imports), D-W-6 (API quota), D-W-7 (contextual numeric rule), D-W-8 (P-4.b not performed author→chat), D-W-9 (CC executed before dispatch/comparator), D-W-10 (CC file absent at first), D-W-11/12/13 (the superseded text: md5 mismatch, E-W-3(a) not honored, placeholders). Q-W-1 (author query: the sealed row's wavenumber ~10⁶ above the named source's orbital-radiation wavenumber; caveat binds an orbital-decay agreement to a carrier group-speed offset — a dialect reading; sealed text dispositive; INERT a fortiori at the lower k). CC: CC-DD-1..7, H-CC-1..2. Standing amendment P-5 (independence witness for every difference-forcing election) PROPOSED, not folded. "
"Registers: R1-machine two-leg for every number; the INERT reading R2 conditional on E-W-1..3, S-W-1 (leading-order additivity of the two scales), E-P2-1 (a), G-POLY1's E3 elections and the Born/SOA order; the polycrystal postulate remains R3. NO observable, NO bridge (M.BRIDGE intact), NO channel-speed-equality claim, NO μ_n, NO d derived, NO reinstatement of W_∪. Successors: none opened by this gate; the multi-species channel-speed question and D-S2C1-1 (single-crystal S9 formal run-2) stand as at V4.80. Folded as one additive bracket on the §2.91.O PF-S2 sentence + one annotation on the Part VI G-POLY1 window row + one Part VI row + this record. Full V4.81 record here. ")
assert s.count(R_ANCH) == 1
# E4 additive V4.81 bracket on the §2.91.O PF-S2 sentence
PF_OLD = "W_∪′ is the named successor mini-gate G-S2C1-W.** Object:"
PF_NEW = ("W_∪′ is the named successor mini-gate G-S2C1-W.** [V4.81: G-S2C1-W EXECUTED and CLOSED two-leg INERT, OOM-ROBUST — with the measured a₂ (lattice, floor ~10⁻⁸¹ under ξ = ℓ_P + the G-C1 C-interval) and a₂^agg (grain) made into `disp` constraint curves against one author-supplied sealed dispersion budget, no edge governs on any arm (Born edges ~10⁵ m, inside the kd ≤ 0.3 envelope); W_∪′ = W_∪ = (0, 2.1213132100130068 m] on hex:step; W_∪ REMAINS SUSPENDED and W_∪′ is BANKED ALONGSIDE it (E-W-7(a)); no reinstatement. Chat af7516c5 / CC 6dde4ae6; comparator v1.1p 55e6977e run 3, zero deviation on every verdict-bearing quantity, C-W-7 independence witness PASS.] Object:")
assert LINE_O.count(PF_OLD) == 1 and s.count(PF_OLD) == 1
LINE_O_NEW = LINE_O.replace(PF_OLD, PF_NEW, 1)
assert s.count(LINE_O_NEW) == 0
# E5 additive V4.81 annotation on the Part VI G-POLY1 window row
ROW_POLY_NEW = ROW_POLY[:-2] + " [V4.81: G-S2C1-W executed — W_∪′ = W_∪ INERT, OOM-ROBUST two-leg (chat af7516c5 / CC 6dde4ae6); the lattice floor VOID-TRIVIAL and the grain-scale `disp` edges non-governing by ~5 orders; W_∪ remains SUSPENDED; W_∪′ banked alongside; no reinstatement (E-W-7(a)).] |"
assert s.count(ROW_POLY_NEW) == 0
# E6 Part VI row (after the G-S2C1 row)
ROW = ("| **Gate G-S2C1-W** (the W_∪′ re-derivation mini-gate, PF-S2 successor; staging memo 1ebb6a82 LOCKED September 8, 2026, lock record 5f963ed8, Addenda 1/2 12580917 / 7cdcf7e6; T1 20ba1e7e ∪ A1 735eae30 = 37 patterns; pinned inputs d1edc69b author-verified; sealed anchor file 8c7d59f6 (one `disp` row, q = group, identifiers masked); G-POLY1 Phase-3 machinery recovered from claude/new-session-e1u91p @ dd813646, MANIFEST 13/13; dispatch 7ca7e9e9, 13 embeds, P-4/P-4.b/P-4.c clean at CC; chat v6.1 e034d428 read #2 af7516c5 (read #1 X-1 H-W-4); CC cd9c21dc on claude/new-session-q8iuz5 @ 4184c2ab / 208902e0, checkpoint 6dde4ae6, report 835c478f; comparators v1.0 007688e5 / v1.1 f27a008f / v1.1p 55e6977e; reconciliation 1f8451e8) "
"| **CLOSED (V4.81)** — INERT, OOM-ROBUST two-leg: W_∪′ = W_∪ = (0, 2.1213132100130068 m] on hex:step; lattice floor ~10⁻⁸¹ (VOID-TRIVIAL as registered); grain-scale Born `disp` edges 1.5–2.2×10⁵ m (kd 0.13–0.19; hex:step DRESSING-SENSITIVE Δ₄ 0.138, non-governing); FAIL-L never fired; ×10 → edges VOIDED beyond the envelope, ×0.1 → non-governing; W_∪ REMAINS SUSPENDED, W_∪′ BANKED ALONGSIDE (E-W-7(a)), no reinstatement. Run 3: 105 items, zero deviation on every verdict-bearing quantity, C-W-7 independence witness PASS (CC F_L = chat × 1.034860); 19 representational/definitional misses disclosed (H-W-6 conceded, reconciled). S9 on a superseded 'CC checkpoint' text (722f0f1d): bit-identical to the chat leg where E-W-3(a) forces a difference — witness FAILED (D-W-11/12/13); v1.1 frozen pre-re-emission (H-W-5); P-5 proposed. Honesty: chat H-W-0..6, D-W-0..13, Q-W-1; CC CC-DD-1..7, H-CC-1..2. R1-machine two-leg; R2 reading conditional on E-W-1..3, S-W-1, E-P2-1 (a), G-POLY1 E3 / Born order; polycrystal postulate R3; no observable, no bridge, no channel-speed claim, no μ_n; §2.52 Open 3 untouched. |")
assert ROW.count("|") == ROW_S2C1.count("|") and s.count(ROW) == 0
# E7 changelog line
CH_NEW = ("*V4.81 (September 9, 2026): additions only — title/As-of header bump (V4.80 → V4.81; As-of date September 6 → September 9), the V4.81 fold-in summary prepended within the accumulated As-of header and the full V4.81 record at the top of the recent fold-in block (before V4.80), "
"one additive V4.81 bracket on the §2.91.O PF-S2 sentence (G-S2C1-W EXECUTED and CLOSED two-leg INERT, OOM-ROBUST; W_∪′ = W_∪ banked alongside the suspended W_∪; no reinstatement), "
"one additive V4.81 annotation on the Part VI G-POLY1 window row, "
"one new Part VI row (Gate G-S2C1-W, after the G-S2C1 row, carrying H-W-0..6, D-W-0..13, Q-W-1, CC-DD-1..7, H-CC-1..2 and the P-5 proposal), and this changelog line. No new §2.x paragraph. The §2.52 Open 3 row untouched (asserted byte-identical). Reverse-splice byte-verified against V4.80 (a28e9b40).*")
assert s.count(CH_NEW) == 0

out = s.replace(T_OLD, T_NEW, 1)
out = out.replace(A_OLD, A_SUM, 1)
out = out.replace(R_ANCH, RECORD + R_ANCH, 1)
out = out.replace("\n" + LINE_O + "\n", "\n" + LINE_O_NEW + "\n", 1)
out = out.replace("\n" + ROW_POLY + "\n", "\n" + ROW_POLY_NEW + "\n", 1)
out = out.replace("\n" + ROW_S2C1 + "\n", "\n" + ROW_S2C1 + "\n" + ROW + "\n", 1)
out = out.replace(LINE_CH80, LINE_CH80 + "\n" + CH_NEW, 1)
O3_POST = [l for l in out.split("\n") if l.startswith("| **§2.52 Open 3**")]
assert O3_POST == [O3_PRE] and out.count(O3_PRE) == 1, "§2.52 Open 3 row changed — halt"
open(OUT, "w", encoding="utf-8", newline="\n").write(out)

rev = open(OUT, encoding="utf-8").read()
rev = rev.replace(LINE_CH80 + "\n" + CH_NEW, LINE_CH80, 1)
rev = rev.replace("\n" + ROW_S2C1 + "\n" + ROW + "\n", "\n" + ROW_S2C1 + "\n", 1)
rev = rev.replace("\n" + ROW_POLY_NEW + "\n", "\n" + ROW_POLY + "\n", 1)
rev = rev.replace("\n" + LINE_O_NEW + "\n", "\n" + LINE_O + "\n", 1)
rev = rev.replace(RECORD + R_ANCH, R_ANCH, 1)
rev = rev.replace(A_SUM, A_OLD, 1)
rev = rev.replace(T_NEW, T_OLD, 1)
rmd5 = hashlib.md5(rev.encode("utf-8")).hexdigest()
assert rmd5 == V480, "REVERSE-SPLICE FAILED: %s" % rmd5
b = open(OUT, "rb").read()
print("V4.81 CANDIDATE STAGED:", OUT)
print("bytes:", len(b), " (V4.80 was %d B; delta +%d B)" % (V480_BYTES, len(b) - V480_BYTES))
print("md5:", hashlib.md5(b).hexdigest())
print("reverse-splice: BYTE-IDENTICAL to V4.80 (%s) — PASS" % V480)
print("§2.52 Open 3: the Part VI row byte-identical and unique — PASS")
