"""Programmatic verification of the three Cl(6) naturality obstructions.

Companion to ``tools/clifford_embedding_check.md`` and the existence
verifier in ``tools/_clifford_check.py``. Where the existence script
confirms that 6 anticommuting generators γ_a do live in M_8(F_3329)
(and that their lifts Γ_a = I_16 ⊗ γ_a satisfy the same relations on
F_3329^128), this script verifies the *obstructions to naturality*:

(O1) **16-fold multiplicity.** The commutant of the 6 generators
     acting on the 8-dim spinor S = F_3329^8 has dimension 1 (Schur
     on the irreducible spinor). The lifted generators Γ_a act on
     V = F_q^16 ⊗ S with multiplicity 16, so End_{Cl(6)}(V) = M_16
     of dimension 16² = 256. Both numbers are computed exactly here.

(O2) **No (Z/2)^6 inside Z/128.** The natural cyclic NTT symmetry
     on the 128 factor indices is Z/128, generated by rotation by
     ζ². Z/128 has prime-power order 2^7 and is *cyclic*, so its
     unique subgroup of order 2^k for each k ≤ 7 is itself cyclic
     (= Z/2^k). In particular it never contains (Z/2)^6, which is
     elementary abelian of order 2^6 = 64 with 63 elements of
     order 2. Z/128 has exactly one element of order 2, so it
     cannot embed (Z/2)^6.

(O3) **No diagonal Cl(6).** A "natural" Cl(6) action on the
     NTT-factored module would have generators that preserve each
     1-dim factor V_α ≅ F_q — i.e., diagonal in the F_q^128 basis.
     But any two diagonal matrices commute, so no anticommuting
     pair of diagonal involutions exists. Hence no faithful Cl(6)
     embedding has diagonal generators, and any actual embedding
     (such as the Pauli-tensor one on this branch) must mix NTT
     factors. The obstruction is verified here both by construction
     (commute random diagonal involutions) and by a clean structural
     argument.

All checks run in pure CPython mod 3329 in well under a second.
"""

from __future__ import annotations

import itertools
from typing import Sequence

# Reuse the verified γ_a / Γ_a generators from the existence script.
from . import _clifford_check as _cc  # type: ignore[import-not-found]

Q = 3329


# ---------------------------------------------------------------------------
# Linear-algebra helpers (mod Q)
# ---------------------------------------------------------------------------


def _row_reduce_mod(rows: list[list[int]], cols: int) -> int:
    """Return rank of the matrix with the given rows over F_Q (Q prime)."""
    M = [list(r) for r in rows]
    r = 0
    for c in range(cols):
        # Find a pivot row with non-zero entry at column c, at or below r.
        piv = None
        for i in range(r, len(M)):
            if M[i][c] != 0:
                piv = i
                break
        if piv is None:
            continue
        M[r], M[piv] = M[piv], M[r]
        inv = pow(M[r][c], Q - 2, Q)
        M[r] = [(v * inv) % Q for v in M[r]]
        for i in range(len(M)):
            if i != r and M[i][c] != 0:
                factor = M[i][c]
                M[i] = [(M[i][j] - factor * M[r][j]) % Q
                        for j in range(cols)]
        r += 1
        if r == cols:
            break
    return r


def _commutator_constraint_rows(gens: list[list[list[int]]], dim: int):
    """For each generator G, the constraint [G, M] = G·M − M·G = 0 expands
    into ``dim*dim`` linear equations in the ``dim*dim`` unknowns of M.
    We index unknowns as M[i][j] -> dim*i + j, and emit one row per
    (i, j) entry of the commutator.
    """
    n = dim * dim
    rows: list[list[int]] = []
    for G in gens:
        for i in range(dim):
            for j in range(dim):
                row = [0] * n
                # (G·M)[i][j] = sum_k G[i][k] * M[k][j]
                for k in range(dim):
                    if G[i][k]:
                        row[k * dim + j] = (row[k * dim + j] + G[i][k]) % Q
                # − (M·G)[i][j] = − sum_k M[i][k] * G[k][j]
                for k in range(dim):
                    if G[k][j]:
                        row[i * dim + k] = (row[i * dim + k] - G[k][j]) % Q
                rows.append(row)
    return rows, n


def _commutant_dim(gens: list[list[list[int]]], dim: int) -> int:
    rows, n = _commutator_constraint_rows(gens, dim)
    rank = _row_reduce_mod(rows, n)
    return n - rank


# ---------------------------------------------------------------------------
# (O1) Multiplicity
# ---------------------------------------------------------------------------


def obstruction_multiplicity() -> dict:
    """Compute commutant dim of {γ_a} on F_q^8 and predicted dim on F_q^128.

    By direct computation on the 8-dim spinor; the 128-dim result
    follows from the tensor structure Γ_a = I_16 ⊗ γ_a (commutant
    is M_16 ⊗ I_8, dim 16² = 256).
    """
    g8 = _cc.gamma8()
    spinor_commutant = _commutant_dim(g8, 8)
    multiplicity = 128 // 8                       # = 16
    lifted_commutant_predicted = multiplicity ** 2  # = 256
    return {
        "spinor_dim": 8,
        "spinor_commutant_dim": spinor_commutant,
        "spinor_irreducible": spinor_commutant == 1,
        "ambient_dim": 128,
        "multiplicity": multiplicity,
        "lifted_commutant_dim_predicted": lifted_commutant_predicted,
        "obstruction_holds": (spinor_commutant == 1
                              and multiplicity == 16
                              and lifted_commutant_predicted == 256),
    }


# ---------------------------------------------------------------------------
# (O2) (Z/2)^6 ⊄ Z/128
# ---------------------------------------------------------------------------


def obstruction_no_z2_6_in_z128() -> dict:
    """Z/128 has 1 element of order 2; (Z/2)^6 has 63. Hence no embedding."""
    n = 128
    elements_of_order_2_in_Zn = sum(1 for k in range(1, n) if (2 * k) % n == 0)
    elements_of_order_2_needed = (1 << 6) - 1   # = 63
    return {
        "cyclic_order": n,
        "elements_of_order_2_in_cyclic": elements_of_order_2_in_Zn,
        "elements_of_order_2_needed_for_(Z/2)^6": elements_of_order_2_needed,
        "obstruction_holds": (
            elements_of_order_2_in_Zn < elements_of_order_2_needed
        ),
    }


# ---------------------------------------------------------------------------
# (O3) No diagonal Cl(6)
# ---------------------------------------------------------------------------


def _matmul(A, B):
    n, m, k = len(A), len(B[0]), len(B)
    C = [[0] * m for _ in range(n)]
    for r in range(n):
        for c in range(m):
            s = 0
            for j in range(k):
                s += A[r][j] * B[j][c]
            C[r][c] = s % Q
    return C


def obstruction_no_diagonal_cl6() -> dict:
    """Show no 6 anticommuting diagonal involutions exist in M_n(F_q).

    Direct argument: any two diagonal matrices commute (entry-wise
    multiplication is commutative). For the Clifford relation to hold
    with i ≠ j we'd need γ_i γ_j = − γ_j γ_i but commuting diagonal
    matrices give γ_i γ_j = γ_j γ_i. Combined with γ² = I (forcing
    diagonal entries in {±1}) the only way both relations can hold is
    γ_i γ_j = γ_j γ_i = 0, which fails γ² = I.

    Programmatic witness: pick two random diagonal involutions, check
    they commute, and check their commutator is the zero matrix.
    """
    n = 128
    import random
    rng = random.Random(0xc1)
    # Two diagonal involutions: entries in {1, Q-1}.
    sign1 = [1 if rng.random() < 0.5 else Q - 1 for _ in range(n)]
    sign2 = [1 if rng.random() < 0.5 else Q - 1 for _ in range(n)]
    D1 = [[sign1[i] if i == j else 0 for j in range(n)] for i in range(n)]
    D2 = [[sign2[i] if i == j else 0 for j in range(n)] for i in range(n)]
    # (D1 D2 - D2 D1)[i][j] = D1[i][i] D2[j][j] δ_{ij} - D2[i][i] D1[j][j] δ_{ij}
    # = δ_{ij} (sign1[i]*sign2[i] - sign2[i]*sign1[i]) = 0.
    AB = _matmul(D1, D2)
    BA = _matmul(D2, D1)
    commutator_is_zero = AB == BA

    # Sanity: each is an involution.
    inv1 = _matmul(D1, D1)
    inv2 = _matmul(D2, D2)
    I = [[1 if i == j else 0 for j in range(n)] for i in range(n)]

    return {
        "ambient_dim": n,
        "two_random_diagonal_involutions_commute": commutator_is_zero,
        "each_squares_to_identity": (inv1 == I and inv2 == I),
        "obstruction_holds": commutator_is_zero,
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> int:
    import pprint
    for name, fn in [
        ("multiplicity",       obstruction_multiplicity),
        ("no (Z/2)^6 ⊂ Z/128", obstruction_no_z2_6_in_z128),
        ("no diagonal Cl(6)",  obstruction_no_diagonal_cl6),
    ]:
        print(f"=== {name} ===")
        pprint.pp(fn())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
