"""Gram-Schmidt profile of the Module-SLWE primal-attack lattice (Brief 05, OP-F).

Question (paraphrased from OP-F): does the Singer-cycle PSL(2,7)
structure imposed on the public matrix ``A`` of Module-SLWE
introduce *exploitable* short vectors in the primal-attack lattice
relative to a uniformly random Module-LWE matrix of the same
dimensions? Concretely: does the Gram-Schmidt profile of the
primal-lattice basis derived from a Singer-orbit ``A`` deviate from
the profile of a uniform-``A`` baseline, and if so by how much?

Setup
-----

- Module rank ``k = 32`` (per Brief 05 §1; reducible to 16 if
  resources are tight, see stop conditions).
- Sedenion dimension ``d = 16``.
- Primary prime ``q = p = 8191`` (smallest mod-455 prime above the
  toy size; preserves PSL(2,7) symmetry of the Singer construction).
- Flatten ``A`` (a ``k × k`` matrix of sedenion entries) into the
  left-multiplication embedding ``A_F`` of shape ``n × n`` with
  ``n = k · d``. Each sedenion entry ``A[i, j]`` becomes the
  ``d × d`` matrix of left-multiplication-by-``A[i, j]`` acting on
  ``S_p ≅ F_p^{16}``. This matches the existing ``rank_flat`` helper
  in ``tools/sqt_slwe.py``.
- Build an ``(n+1) × (n+1)`` primal-attack basis ``B`` whose first
  ``n`` rows are the rows of ``A_F`` and whose last row is the
  Kannan-style ``q``-tag ``(q, 0, …, 0, 1)``. The lattice
  generated by these rows is

      L = span_Z{ A_F-rows, (q, 0, …, 0, 1) }.

  This is a deliberately simple primal embedding chosen to expose
  any structural anomaly in ``A_F`` itself: the first ``n``
  ``b*_i`` come directly from Gram-Schmidting the rows of ``A_F``,
  so the GS norms of those rows are *the* observable for OP-F.

GS computation
--------------

Two backends:

- ``fpylll`` ``GSO.Mat(..., float_type='mpfr')`` for high-precision
  Gram-Schmidt over the lifted integer basis. Preferred at this
  scale.
- ``numpy.float64`` Gram-Schmidt as a fallback when fpylll isn't
  importable. Notes precision concerns inline.

The script reports the log_2 GS norms, the slope of the log
profile, the deviation from the Geometric Series Assumption (GSA)
prediction at every position, and the maximum log_2-deviation
between the Singer profile and the random baseline at any index.
A max deviation > 0.5 (T1 flag set by the brief) indicates a
potential structural weakness.
"""

from __future__ import annotations

import json
import math
import random
import sys
import time
from pathlib import Path

# Pull in the existing sedenion helpers and Singer construction.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from sedenion_Fp import DIM as _DIM  # noqa: E402
from sedenion_Fp import basis_vec, mul_vec  # noqa: E402
import sqt_slwe as _slwe  # noqa: E402

# ---------------------------------------------------------------------------
# Backend selection
# ---------------------------------------------------------------------------


def _have_fpylll() -> bool:
    try:
        import fpylll  # noqa: F401
        return True
    except Exception:
        return False


def _have_numpy() -> bool:
    try:
        import numpy  # noqa: F401
        return True
    except Exception:
        return False


# ---------------------------------------------------------------------------
# Sedenion → F_p matrix flattening (left-multiplication block embedding)
# ---------------------------------------------------------------------------


def _lmm_block(s: list[int], p: int) -> list[list[int]]:
    """16×16 matrix of left-multiplication by sedenion ``s`` over F_p."""
    B = [[0] * _DIM for _ in range(_DIM)]
    for j in range(_DIM):
        col = mul_vec(s, basis_vec(j), p)
        for i in range(_DIM):
            B[i][j] = col[i]
    return B


def flatten_sedenion_matrix(M_sed: list[list[list[int]]],
                            p: int) -> list[list[int]]:
    """``k × k`` sedenion matrix → ``(k·DIM) × (k·DIM)`` F_p matrix."""
    k = len(M_sed)
    n = k * _DIM
    A_flat = [[0] * n for _ in range(n)]
    for i in range(k):
        for j in range(k):
            block = _lmm_block(M_sed[i][j], p)
            for r2 in range(_DIM):
                for c2 in range(_DIM):
                    A_flat[i * _DIM + r2][j * _DIM + c2] = block[r2][c2]
    return A_flat


# ---------------------------------------------------------------------------
# Construct Singer-orbit A and random-A matrices
# ---------------------------------------------------------------------------


def make_singer_A(k: int, p: int, rng: random.Random) -> list[list[list[int]]]:
    # The supplied source uses Python's ``random`` module globally; reseed it
    # from our local rng so the construction is deterministic per (k, p, rng).
    _slwe.p = p
    import random as _grn
    _grn.seed(rng.randrange(0, 1 << 31))
    A: list[list[list[int]]] = []
    for _ in range(k):
        seed = _slwe.rand_nonzd()
        A.append(_slwe.singer_orbit(seed, k))
    return A


def make_random_A(k: int, p: int, rng: random.Random) -> list[list[list[int]]]:
    """Sedenion-shaped uniform A (no Singer structure)."""
    A: list[list[list[int]]] = []
    for _ in range(k):
        row: list[list[int]] = []
        for _ in range(k):
            row.append([rng.randrange(0, p) for _ in range(_DIM)])
        A.append(row)
    return A


# ---------------------------------------------------------------------------
# Primal-attack lattice basis
# ---------------------------------------------------------------------------


def primal_basis(A_flat: list[list[int]], q: int) -> list[list[int]]:
    """Build an ``(n+1)×(n+1)`` Z-basis from ``A_flat`` rows and a q-tag."""
    n = len(A_flat)
    B = [row + [0] for row in A_flat]            # n × (n+1)
    tag = [q] + [0] * (n - 1) + [1]              # (q, 0, …, 0, 1)
    B.append(tag)
    return B                                      # (n+1) × (n+1)


# ---------------------------------------------------------------------------
# Gram-Schmidt
# ---------------------------------------------------------------------------


def gs_norms_fpylll(B: list[list[int]], float_type: str = "mpfr",
                    precision: int = 200) -> list[float]:
    from fpylll import IntegerMatrix, GSO, FPLLL  # type: ignore[import-not-found]
    if float_type == "mpfr":
        FPLLL.set_precision(precision)
    M_int = IntegerMatrix.from_matrix(B)
    M = GSO.Mat(M_int, float_type=float_type)
    M.update_gso()
    n = len(B)
    out = []
    for i in range(n):
        r = float(M.get_r(i, i))
        # Tiny negatives are mpfr round-off on residuals that are exactly
        # zero (rank-deficient rows). Clip to 0; the caller distinguishes
        # zero from small via a floor.
        if r < 0:
            r = 0.0
        out.append(math.sqrt(r))
    return out


def gs_norms_numpy(B: list[list[int]]) -> list[float]:
    import numpy as np  # type: ignore[import-not-found]
    A = np.asarray(B, dtype=np.float64)
    n = A.shape[0]
    norms = np.empty(n)
    Bstar = np.zeros_like(A)
    for i in range(n):
        v = A[i].copy()
        for j in range(i):
            denom = float(np.dot(Bstar[j], Bstar[j]))
            if denom == 0:
                continue
            v -= (np.dot(Bstar[j], A[i]) / denom) * Bstar[j]
        Bstar[i] = v
        norms[i] = float(np.linalg.norm(v))
    return norms.tolist()


def _matrix_rank_mod_p(M: list[list[int]], p: int) -> int:
    """Rank of an integer matrix considered mod prime p, via Gaussian elimination.

    F_p-rank is a lower bound for Z-rank (and an upper bound for the rank of
    the lattice of integer combinations of the rows, since dependencies over Z
    descend to dependencies over F_p). For our purposes here — distinguishing
    a rank-deficient Singer A_F from a full-rank random A_F — the F_p rank
    is the tight signal.
    """
    A = [[x % p for x in row] for row in M]
    rows = len(A)
    cols = len(A[0]) if rows else 0
    rank = 0
    for c in range(cols):
        if rank >= rows:
            break
        piv = None
        for r in range(rank, rows):
            if A[r][c] % p != 0:
                piv = r
                break
        if piv is None:
            continue
        A[rank], A[piv] = A[piv], A[rank]
        inv = pow(A[rank][c], p - 2, p)
        A[rank] = [(x * inv) % p for x in A[rank]]
        for r in range(rows):
            if r != rank and A[r][c] % p != 0:
                f = A[r][c]
                A[r] = [(A[r][j] - f * A[rank][j]) % p for j in range(cols)]
        rank += 1
    return rank


def _column_period(M: list[list[int]]) -> int | None:
    """Smallest d ≥ 1 such that column j and column j+d are *identical* over Z
    for every valid j. Returns None if no such d exists below n_cols."""
    rows = len(M)
    cols = len(M[0]) if rows else 0
    for d in range(1, cols):
        ok = True
        for j in range(cols - d):
            for i in range(rows):
                if M[i][j] != M[i][j + d]:
                    ok = False
                    break
            if not ok:
                break
        if ok:
            return d
    return None


def gs_norms(B: list[list[int]], backend: str = "auto") -> tuple[list[float], str]:
    if backend == "auto":
        backend = "fpylll" if _have_fpylll() else ("numpy" if _have_numpy()
                                                    else "none")
    if backend == "fpylll":
        return gs_norms_fpylll(B), "fpylll-mpfr-200"
    if backend == "numpy":
        return gs_norms_numpy(B), "numpy-float64"
    raise RuntimeError("no GS backend available")


# ---------------------------------------------------------------------------
# Profile statistics
# ---------------------------------------------------------------------------


def gsa_predicted_slope(B_norms: list[float], n_for_volume: int) -> float:
    """Slope of log_2 ‖b*_i‖ vs i predicted by the Geometric Series Assumption.

    For a basis of dim n+1 with volume V, GSA says
       log_2 ‖b*_i‖ ≈ log_2(V^{1/(n+1)}) + (n - 2 i) / 2 · δ
    where δ is the half-slope. Without BKZ reduction the GSA isn't a
    great fit; we report the *least-squares slope* of the actual log
    profile, which is what an attacker would compare against.
    """
    log_norms = [math.log2(max(b, 1e-300)) for b in B_norms]
    n = len(log_norms)
    xs = list(range(n))
    mean_x = sum(xs) / n
    mean_y = sum(log_norms) / n
    num = sum((x - mean_x) * (y - mean_y) for x, y in zip(xs, log_norms))
    den = sum((x - mean_x) ** 2 for x in xs)
    slope = num / den if den else 0.0
    intercept = mean_y - slope * mean_x
    return slope, intercept


def deviation_from_line(log_norms: list[float], slope: float,
                        intercept: float) -> list[float]:
    return [log_norms[i] - (slope * i + intercept)
            for i in range(len(log_norms))]


# ---------------------------------------------------------------------------
# Main driver
# ---------------------------------------------------------------------------


_ZERO_FLOOR = 1e-10   # below this we treat the GS norm as "effectively zero".
                       # Empirically there is a clean gap between rank-deficient
                       # residuals (∼ 1e-50 in mpfr-200) and the smallest real
                       # short vectors (≥ 1) for our integer bases.
_LOG_FLOOR = -100     # log_2 substitute for "effectively zero" rows


def run_profile(k: int, p: int, *, seed: int = 0xb05) -> dict:
    rng_singer = random.Random(seed)
    rng_random = random.Random(seed + 1)

    t0 = time.monotonic()
    A_singer = make_singer_A(k, p, rng_singer)
    A_random = make_random_A(k, p, rng_random)
    t_construct = time.monotonic() - t0

    t0 = time.monotonic()
    Asf = flatten_sedenion_matrix(A_singer, p)
    Arf = flatten_sedenion_matrix(A_random, p)
    t_flatten = time.monotonic() - t0

    # F_p-rank of each A_F. Lower bound on Z-rank; tight here because we
    # also detect Z-column equalities directly via _column_period.
    t0 = time.monotonic()
    s_fp_rank = _matrix_rank_mod_p(Asf, p)
    r_fp_rank = _matrix_rank_mod_p(Arf, p)
    s_col_period = _column_period(Asf)
    r_col_period = _column_period(Arf)
    t_rank = time.monotonic() - t0

    n = len(Asf)
    Bs = primal_basis(Asf, p)
    Br = primal_basis(Arf, p)

    t0 = time.monotonic()
    s_norms, backend = gs_norms(Bs)
    r_norms, _ = gs_norms(Br)
    t_gs = time.monotonic() - t0

    def _safe_log2(b: float) -> float:
        return math.log2(b) if b > _ZERO_FLOOR else _LOG_FLOOR

    s_log = [_safe_log2(b) for b in s_norms]
    r_log = [_safe_log2(b) for b in r_norms]
    s_zero_count = sum(1 for b in s_norms if b <= _ZERO_FLOOR)
    r_zero_count = sum(1 for b in r_norms if b <= _ZERO_FLOOR)
    # Fit the slope on the first n rows (the A_F-derived rows), excluding
    # zero-residual rows (they're the rank deficit, not part of the GSA-line
    # signal). The last row is the Kannan q-tag and is also excluded.
    s_nonzero = [b for b in s_norms[:n] if b > _ZERO_FLOOR]
    r_nonzero = [b for b in r_norms[:n] if b > _ZERO_FLOOR]
    s_slope, s_intercept = gsa_predicted_slope(s_nonzero, n) \
        if s_nonzero else (0.0, 0.0)
    r_slope, r_intercept = gsa_predicted_slope(r_nonzero, n) \
        if r_nonzero else (0.0, 0.0)
    s_dev_full = deviation_from_line(s_log, s_slope, s_intercept)
    r_dev_full = deviation_from_line(r_log, r_slope, r_intercept)
    s_dev = s_dev_full[:n]
    r_dev = r_dev_full[:n]

    # Compare Singer vs Random over indices 0..n-1, separately for
    # "both nonzero" (apples-to-apples profile-shape comparison) and "rank
    # collapse" (Singer drops to zero where Random doesn't — the smoking gun).
    both_nz_indices = [i for i in range(n)
                       if s_norms[i] > _ZERO_FLOOR and r_norms[i] > _ZERO_FLOOR]
    rank_collapse_indices = [i for i in range(n)
                              if s_norms[i] <= _ZERO_FLOOR < r_norms[i]]
    if both_nz_indices:
        nz_diffs = [s_log[i] - r_log[i] for i in both_nz_indices]
        max_abs_diff = max(abs(d) for d in nz_diffs)
        max_diff_index = both_nz_indices[
            max(range(len(nz_diffs)), key=lambda j: abs(nz_diffs[j]))]
    else:
        max_abs_diff = 0.0
        max_diff_index = 0
    diff = [s_log[i] - r_log[i] for i in range(n)]

    s_dev_std = (sum(d * d for d in s_dev) / max(1, len(s_dev))) ** 0.5
    r_dev_std = (sum(d * d for d in r_dev) / max(1, len(r_dev))) ** 0.5
    s_max_dev = max((abs(d) for d in s_dev), default=0.0)
    r_max_dev = max((abs(d) for d in r_dev), default=0.0)
    # Indices where Singer deviates more than 2 sigma from its own GSA line.
    s_two_sigma = [i for i, d in enumerate(s_dev) if abs(d) > 2 * s_dev_std]

    return {
        "k": k,
        "p": p,
        "n": n,
        "basis_dim": n + 1,
        "backend": backend,
        "construct_seconds": t_construct,
        "flatten_seconds": t_flatten,
        "rank_seconds": t_rank,
        "gs_seconds": t_gs,
        "singer_fp_rank": s_fp_rank,
        "random_fp_rank": r_fp_rank,
        "singer_column_period": s_col_period,
        "random_column_period": r_col_period,
        "singer_gs_zero_count": s_zero_count,
        "random_gs_zero_count": r_zero_count,
        "zero_floor": _ZERO_FLOOR,
        "singer": {
            "log2_norms": s_log,
            "slope": s_slope,
            "intercept": s_intercept,
            "max_abs_dev_from_line": s_max_dev,
            "rms_dev_from_line": s_dev_std,
        },
        "random": {
            "log2_norms": r_log,
            "slope": r_slope,
            "intercept": r_intercept,
            "max_abs_dev_from_line": r_max_dev,
            "rms_dev_from_line": r_dev_std,
        },
        "comparison": {
            "max_abs_log2_diff_on_both_nonzero": max_abs_diff,
            "max_diff_index": max_diff_index,
            "rank_collapse_index_count": len(rank_collapse_indices),
            "rank_collapse_first_indices": rank_collapse_indices[:8],
            "weakness_flag_05_threshold": (
                max_abs_diff > 0.5 or len(rank_collapse_indices) > 0
            ),
            "singer_two_sigma_indices": s_two_sigma,
        },
    }


def render_ascii_profile(log_norms: list[float], width: int = 60,
                         height: int = 14) -> str:
    if not log_norms:
        return ""
    lo, hi = min(log_norms), max(log_norms)
    rng = max(1e-9, hi - lo)
    cols = []
    step = max(1, len(log_norms) // width)
    for i in range(0, len(log_norms), step):
        v = log_norms[i]
        bar = int(round((v - lo) / rng * (height - 1)))
        cols.append(bar)
    out = []
    for h in range(height - 1, -1, -1):
        line = ["  "]
        for c in cols:
            line.append("#" if c >= h else " ")
        out.append("".join(line))
    out.append("  " + "-" * len(cols))
    return "\n".join(out)


def main() -> int:
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--k", type=int, default=32)
    p.add_argument("--p", type=int, default=8191)
    p.add_argument("--out-json",
                   default="tools/gs_profile_results.json", type=Path)
    args = p.parse_args()

    result = run_profile(args.k, args.p)
    args.out_json.write_text(json.dumps(result, indent=2) + "\n")
    print(f"backend = {result['backend']}")
    print(f"k = {result['k']}, n = {result['n']}, basis dim = {result['basis_dim']}")
    print(f"construct {result['construct_seconds']:.1f}s, "
          f"flatten {result['flatten_seconds']:.1f}s, "
          f"rank {result['rank_seconds']:.1f}s, "
          f"GS {result['gs_seconds']:.1f}s")
    print(f"\n{'matrix':<10} {'F_p rank':>10} {'col-period':>11} "
          f"{'zero GS':>9} (out of n={result['n']})")
    print(f"{'singer':<10} {result['singer_fp_rank']:>10} "
          f"{str(result['singer_column_period']):>11} "
          f"{result['singer_gs_zero_count']:>9}")
    print(f"{'random':<10} {result['random_fp_rank']:>10} "
          f"{str(result['random_column_period']):>11} "
          f"{result['random_gs_zero_count']:>9}")
    s = result["singer"]; r = result["random"]
    print(f"\nSinger log_2 norms: first 5 = {[round(x, 2) for x in s['log2_norms'][:5]]}, "
          f"last 5 = {[round(x, 2) for x in s['log2_norms'][-5:]]}")
    print(f"Random log_2 norms: first 5 = {[round(x, 2) for x in r['log2_norms'][:5]]}, "
          f"last 5 = {[round(x, 2) for x in r['log2_norms'][-5:]]}")
    print(f"\nSinger slope = {s['slope']:.5f}  rms-dev = {s['rms_dev_from_line']:.3f}  "
          f"max-dev = {s['max_abs_dev_from_line']:.3f}")
    print(f"Random slope = {r['slope']:.5f}  rms-dev = {r['rms_dev_from_line']:.3f}  "
          f"max-dev = {r['max_abs_dev_from_line']:.3f}")
    cmp = result["comparison"]
    print(f"\nRank-collapse indices (Singer GS≈0 where Random≠0): "
          f"{cmp['rank_collapse_index_count']} "
          f"(first 8: {cmp['rank_collapse_first_indices']})")
    print(f"Max |Singer - Random| log_2 on both-nonzero indices: "
          f"{cmp['max_abs_log2_diff_on_both_nonzero']:.3f} "
          f"at index {cmp['max_diff_index']}  "
          f"({'FLAG' if cmp['weakness_flag_05_threshold'] else 'no flag'})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
