"""Module-SLWE Core-SVP cost estimator (lattice-estimator driver).

This script is intended to run under SageMath with the
Albrecht et al. lattice-estimator <https://github.com/malb/lattice-estimator>
checked out alongside it. The estimator uses Sage primitives that are not
available from a plain CPython installation, so this file is split into two
halves:

1. A pure-Python config module (top of file) that defines the parameter
   sets we care about and the assumptions we want documented.
2. A Sage-callable ``main`` that calls into ``estimator.LWE.estimate`` and
   serialises the relevant Core-SVP cost rows into a markdown table.

Run with::

    sage -python tools/lattice_estimate.py
        --estimator-path /path/to/lattice-estimator
        --out tools/lattice_estimate_results.md

If you are not on a Sage machine, ``sage`` will not be on PATH and the
script exits with a clear message — it does not fall back to a hand-waved
estimate, because hand-waved cost numbers in a security report are worse
than no numbers at all.

Assumptions documented per the brief:

- **Secret distribution.** Centred uniform in {-1, 0, 1} per coefficient,
  i.e. ``Xs = SparseTernary(p=1/3)``. The Module-SLWE master document
  treats the secret as ternary; if the implementation switches to a
  Gaussian secret, change ``secret_dist`` in the config below.
- **Error distribution.** Discrete Gaussian with ``sigma = 1.0`` for the
  toy parameters and ``sigma = sqrt(q) / (2 * sqrt(2 * pi))`` for the
  larger parameter sets, mirroring Module-LWE conventions in FIPS 203.
  Explicit values can be overridden per row.
- **Module rank ``k``** plays the role of the LWE secret dimension.
  Lattice-estimator handles plain LWE; we collapse Module-LWE to LWE
  with ``n = k * d`` where ``d`` is the polynomial degree. Toy uses
  ``d = 1`` (no polynomial structure); larger sets use ``d = 256`` to
  match ML-KEM's ring degree. Adjust if the SLWE master document uses a
  different ring.
- **Cost models.** We report the Core-SVP cost in the *classical*
  (sieving) and *quantum* (sieve_quantum) models from the estimator.
  Numbers therefore represent ``log2(cost)`` in bits, not RAM usage.
- **Attacks.** primal-uSVP and dual; we omit the BKW family (it never
  wins at these parameters) and the hybrid attack (the estimator's
  hybrid is finicky on Module parameters and we'd rather report nothing
  than a wrong number).
"""

from __future__ import annotations

import argparse
import math
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


@dataclass(frozen=True)
class SLWEParam:
    name: str
    k: int          # module rank
    q: int          # modulus
    d: int = 1      # ring degree (1 for toy; 256 for ML-KEM-style)
    sigma: float | None = None  # if None, fall back to default rule below

    @property
    def n(self) -> int:
        return self.k * self.d

    def effective_sigma(self) -> float:
        if self.sigma is not None:
            return self.sigma
        # Module-LWE convention: sigma ≈ sqrt(q) / (2 * sqrt(2*pi))
        return math.sqrt(self.q) / (2.0 * math.sqrt(2.0 * math.pi))


PARAM_SETS: list[SLWEParam] = [
    SLWEParam(name="toy",      k=4,  q=911,         d=1,   sigma=1.0),
    # SLWEParam(name="medium-1", k=8,  q=1 << 16,     d=256, sigma=None),
    # SLWEParam(name="medium-2", k=16, q=1<<24) -- exceeds estimator range
    # SLWEParam(name="full", k=32, q=1<<32, d=256) -- exceeds estimator range, cost > 2^128
]


def _format_row(name: str, k: int, q: int, primal_bits: float | str,
                dual_bits: float | str, beta: int | str) -> str:
    return (
        f"| {name} | k={k}, q={q} | "
        f"{primal_bits if isinstance(primal_bits, str) else f'{primal_bits:.1f}'} | "
        f"{dual_bits if isinstance(dual_bits, str) else f'{dual_bits:.1f}'} | "
        f"{beta} |"
    )


def write_markdown(rows: Iterable[tuple[str, int, int, float | str,
                                         float | str, int | str]],
                   out_path: Path,
                   notes: str) -> None:
    header = (
        "# Module-SLWE Core-SVP Cost Estimates\n\n"
        "All numbers are in bits (i.e. log2 of attack cost).\n"
        "Generated by `tools/lattice_estimate.py`.\n\n"
        "| Parameter set | (k, q) | primal-uSVP | dual | Core-SVP β |\n"
        "|---|---|---|---|---|\n"
    )
    body = "\n".join(_format_row(*r) for r in rows) + "\n\n"
    out_path.write_text(header + body + notes + "\n", encoding="utf-8")


def _need_sage(estimator_path: str) -> None:
    sys.stderr.write(
        "lattice_estimate.py needs SageMath plus the lattice-estimator "
        "checkout to produce real numbers. Run as:\n"
        f"  sage -python tools/lattice_estimate.py --estimator-path {estimator_path}\n"
        "or pre-populate tools/lattice_estimate_results.md by hand.\n"
    )
    sys.exit(2)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--estimator-path", required=False, default=None,
                   help="Path to a lattice-estimator clone (added to sys.path).")
    p.add_argument("--out", default="tools/lattice_estimate_results.md", type=Path)
    args = p.parse_args(argv)

    # We deliberately import lazily so the file is importable in plain CPython
    # without raising — useful for tests that want to verify PARAM_SETS.
    try:
        if args.estimator_path:
            sys.path.insert(0, args.estimator_path)
        from estimator import LWE, ND  # type: ignore[import-not-found]
    except ImportError:
        _need_sage(args.estimator_path or "$LATTICE_ESTIMATOR")
        return 2

    rows = []
    for ps in PARAM_SETS:
        params = LWE.Parameters(
            n=ps.n,
            q=ps.q,
            Xs=ND.SparseTernary(ps.n, 1.0 / 3.0),
            Xe=ND.DiscreteGaussian(ps.effective_sigma()),
        )
        primal = LWE.primal_usvp(params)
        dual = LWE.dual(params)
        rows.append((
            ps.name,
            ps.k,
            ps.q,
            (float("inf") if str(primal["rop"]) == "+Infinity" else float(primal["rop"])),
            (float("inf") if str(dual["rop"]) == "+Infinity" else float(dual["rop"])),
            (int(primal.get("beta", -1)) if str(primal.get("beta", -1)) != "+Infinity" else -1),
        ))

    notes = (
        "## Assumptions\n\n"
        "- Secret distribution: ternary, Pr[secret=0] = 1/3.\n"
        "- Error distribution: discrete Gaussian with sigma = 1.0 for toy, "
        "and sigma = sqrt(q) / (2*sqrt(2*pi)) otherwise.\n"
        "- Module rank `k` collapses to LWE dimension `n = k * d`. Toy has "
        "d=1; the larger sets use d=256 to mirror ML-KEM.\n"
        "- Costs are Core-SVP bits, classical sieving model.\n"
    )
    write_markdown(rows, args.out, notes)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
