"""Tests for op_2_58_2d_classifier (Brief 07, item 2). Toy scale p=911 only.

CANDIDATE-CUTOFF FOOTNOTE (brief §2.6 — Q1, Q2)

Q1: Does the §2.66.2 work have a precedent for the factor-of-2 cutoff
    ("short basis vectors = those with norm at most twice the shortest
    output norm at that β"), or is it new to OP-2.58.2d?

    ANSWER: No precedent can be found, because the §2.66.2 source
    (op_2_58_2_leakage_test.py, op_2_58_2b_advanced_attacks.py) is NOT
    present in the repo. A repo-wide search for the cutoff returns
    nothing. On the available evidence the factor-of-2 must be treated
    as a NEW pre-registered parameter introduced by OP-2.58.2d, and §3.3
    measurement (1) should name it as such in a pre-freeze revision
    (e.g. "candidate-cutoff factor c = 2, pre-registered here").

Q2: What is the empirical distribution of (number of vectors passing the
    cutoff) on the toy-run fixtures? Is the factor of 2 doing meaningful
    work, or degenerate?

    ANSWER (partial — see report): the cutoff is defined against "the
    shortest output norm at that β", i.e. against BKZ output. No BKZ runs
    exist yet (item 4 / op_2_58_2d_bkz_driver.py is a separate task), so
    the cutoff cannot be exercised on real reduced bases here. As a
    stand-in, test_candidate_cutoff_is_not_degenerate_on_fixtures measures
    the cutoff on the synthetic fixture norms: with random 𝕊_911^7 vectors
    the norms are tightly concentrated (all within a small band of the
    mean), so a factor-of-2 cutoff is a near-no-op on *random* vectors —
    it admits essentially all of them. That is expected and not a defect:
    the cutoff is meant to filter BKZ output, where the shortest vector is
    genuinely shorter than the bulk. The operative Q2 answer ("is the
    factor of 2 doing meaningful work?") is DEFERRED to the BKZ smoke test
    (item 4) where real short-vs-bulk norm separation exists. Recommended
    pre-freeze note in §3.3: state that the cutoff is calibrated against
    BKZ output norm structure, not against the ambient candidate
    distribution.

BIT-EXACTNESS (brief §2.3): UNVERIFIABLE here — the §2.66.2 classifier
source is absent. The fixtures are Path B (regenerated by the classifier
under test); see the circularity caveat in the fixtures JSON header and
op_2_58_2d_prefreeze_report.md. The independent_checks in the fixtures
(analytic closure = 1.0) are the non-circular cross-check.
"""

from __future__ import annotations

import json
import math
import os

import numpy as np
import pytest

from tools.op_2_58_2d_classifier import (
    FanoLineClassifier,
    TOY_P,
    _clean_kernel_vectors,
)

FIXTURES = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "fixtures",
    "op_2_58_2d_classifier_fixtures.json",
)


@pytest.fixture(scope="module")
def clf():
    return FanoLineClassifier(TOY_P)


@pytest.fixture(scope="module")
def fixtures():
    with open(FIXTURES) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# §2.5 test 1 — fixture round-trip (Path B self-consistency)
# ---------------------------------------------------------------------------


def test_fixture_round_trip(clf, fixtures):
    """Re-running the classifier on each saved v reproduces the saved
    argmax line, argmax pair, and ratios (within 1 ulp on the ratios).

    NOTE: this is a self-consistency / regression check, NOT bit-exactness
    against §2.66.2 (whose source is absent). See module docstring."""
    for rec in fixtures["records"]:
        res = clf.classify(rec["v"])
        assert sorted(res["fano_line"]) == rec["fano_line"]
        assert list(res["pair"]) == rec["pair"]
        assert math.isclose(res["fano_ratio"], rec["fano_ratio"], rel_tol=0, abs_tol=1e-12)
        assert math.isclose(res["pair_ratio"], rec["pair_ratio"], rel_tol=0, abs_tol=1e-12)


def test_independent_closure_checks(clf, fixtures):
    """Non-circular cross-check: clean K_(a,b) basis vectors have analytic
    in-subspace closure ratio = 1.0 on their own pair-kernel."""
    for chk in fixtures["independent_checks"]:
        a, b = chk["pair"]
        ratios = clf.pair_ratios(chk["v"])
        assert math.isclose(ratios[(a, b)], 1.0, abs_tol=1e-9)


# ---------------------------------------------------------------------------
# §2.5 test 2 — projection invariance (ratios in [0,1])
# ---------------------------------------------------------------------------


def test_projection_ratios_in_unit_interval(clf, fixtures):
    for rec in fixtures["records"][:100]:
        for ratio in clf.fano_ratios(rec["v"]).values():
            assert -1e-12 <= ratio <= 1.0 + 1e-12
        for ratio in clf.pair_ratios(rec["v"]).values():
            assert -1e-12 <= ratio <= 1.0 + 1e-12


# ---------------------------------------------------------------------------
# §2.5 test 3 — subspace closure (adjusted; see FINDING)
# ---------------------------------------------------------------------------


def test_in_subspace_closure_is_one(clf):
    """A vector lying in F_L projects onto F_L with ratio exactly 1.0."""
    for L in clf.lines:
        a, b, c = sorted(L)
        kv = _clean_kernel_vectors(a, b, TOY_P)[0]  # in K_(a,b) ⊂ F_L
        assert math.isclose(clf.fano_ratios(kv)[L], 1.0, abs_tol=1e-9)


def test_fano_subspaces_overlap_finding(clf):
    """FINDING (for §3.3 pre-freeze revision): the seven F_L subspaces are
    NOT pairwise disjoint. A clean K_(1,2) basis vector lies in F_L at ratio
    1.0 for *two* lines, not one — the kernel-involution overlap. This makes
    §2.5 test 3's strict 'ratio < 1 for all L' ≠ L' FALSE by construction.
    We assert the overlap exists so the finding is a regression check."""
    kv = _clean_kernel_vectors(1, 2, TOY_P)[0]
    ratios = clf.fano_ratios(kv)
    at_unity = [L for L, r in ratios.items() if r > 1.0 - 1e-9]
    assert len(at_unity) >= 2, (
        "expected the kernel-involution overlap (≥2 lines at ratio 1.0); "
        "if this fails the F_L geometry changed"
    )


# ---------------------------------------------------------------------------
# §2.5 test 4 — random baseline sanity
# ---------------------------------------------------------------------------


def test_random_baseline_near_one_seventh(clf):
    """Argmax-Fano-line selection frequency on uniform random 𝕊_911^7 vectors
    is ≈ 1/7 per line, within the brief's ±~1.1% tolerance."""
    rng = np.random.default_rng(20260527)
    N = 1000
    counts = {L: 0 for L in clf.lines}
    for _ in range(N):
        v = rng.integers(0, TOY_P, size=16 * 7)
        counts[clf.classify(v)["fano_line"]] += 1
    for L, ct in counts.items():
        freq = ct / N
        assert abs(freq - 1 / 7) < 0.035, f"line {sorted(L)} freq {freq:.3f} off chance"


# ---------------------------------------------------------------------------
# Substantive validation: recovery on planted ZD-noise (the §2.66.2 setup)
# ---------------------------------------------------------------------------


def test_planted_zd_noise_recovery_far_above_chance(clf):
    """Random α∈{-1,0,1} combinations of K_(a,b) basis vectors are recovered
    by the pair classifier well above the 1/21 chance baseline (reproduces
    the §2.66.2-class strong-recovery behaviour: ~96% pair, ~88% line)."""
    rng = np.random.default_rng(20260527)
    pair_to_line = {}
    for L in clf.lines:
        a, b, c = sorted(L)
        for pr in [(a, b), (a, c), (b, c)]:
            pair_to_line[pr] = L
    N = 300
    pair_hits = 0
    line_hits = 0
    for _ in range(N):
        a, b = clf.pairs[rng.integers(len(clf.pairs))]
        basis = _clean_kernel_vectors(a, b, TOY_P)
        while True:
            alpha = rng.integers(-1, 2, size=4)
            if alpha.any():
                break
        z = sum(al * bv for al, bv in zip(alpha, basis))
        res = clf.classify(z)
        pair_hits += res["pair"] == (a, b)
        line_hits += res["fano_line"] == pair_to_line[(a, b)]
    # Far above chance (1/21 ≈ 4.8% pair, 1/7 ≈ 14.3% line).
    assert pair_hits / N > 0.80
    assert line_hits / N > 0.70


# ---------------------------------------------------------------------------
# Subspace dimensions (pre-reg §2.1: 16→4 and 16→8)
# ---------------------------------------------------------------------------


def test_subspace_dimensions(clf):
    assert all(clf.pair_subspace_dim(p) == 4 for p in clf.pairs)
    assert all(clf.fano_subspace_dim(L) == 8 for L in clf.lines)


# ---------------------------------------------------------------------------
# §2.6 Q2 — candidate cutoff behaviour on the fixture norms
# ---------------------------------------------------------------------------


def test_candidate_cutoff_is_not_degenerate_on_fixtures(fixtures):
    """Measure how many fixture vectors pass a factor-of-2 norm cutoff
    (norm ≤ 2 · min norm). On uniform random 𝕊_911^7 vectors the norms are
    tightly concentrated, so the cutoff admits essentially all of them — a
    near-no-op on random candidates. This documents (not asserts a target
    for) the Q2 finding: the factor-of-2 is calibrated against BKZ output
    norm structure, not the ambient candidate distribution. The real Q2
    answer is deferred to the BKZ smoke test (item 4)."""
    norms = [math.sqrt(sum((x if x <= TOY_P // 2 else x - TOY_P) ** 2 for x in rec["v"]))
             for rec in fixtures["records"]]
    min_norm = min(norms)
    n_pass = sum(1 for nrm in norms if nrm <= 2 * min_norm)
    frac = n_pass / len(norms)
    # On random vectors the cutoff is near-no-op: it admits almost everything.
    assert frac > 0.95, (
        f"factor-of-2 cutoff admitted only {frac:.1%} of random fixtures; "
        "unexpectedly selective on the ambient distribution"
    )
